[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=62.4.0", "wheel"]

[project]
authors = [{ name = "Alexis Purslane" }]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
description = "A proof-of-concept tree-sitter grammar for English prose"
keywords = ["incremental", "parsing", "tree-sitter", "english"]
license.text = "MIT"
name = "tree-sitter-english"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"

[project.urls]
Homepage = "https://tangled.org/xenolandscapes.com/tree-sitter-english"

[project.optional-dependencies]
core = ["tree-sitter~=0.24"]

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
