//! Sentence-length + clause-complexity eval: 60 sentences
//! (15 Moby monsters + 10 Austen monsters + 12 judged sweep mediums +
//! 23 shorts). Hand-labeled complex/long (thresholds: over 30 pieces,
//! 4+ clauses, 2+ subordinate — judgment calls on the boundary,
//! noted below).
//!
//! Gold notes: monsters trivially fire (pipeline-robustness bulk);
//! shorts trivially silent; the 12 mediums carry the calibration
//! (incl. 3 honest negatives: p1908s0/p1016s0/p1326s2 clean despite
//! coordination, p259s2 31-word descriptive flow judged fine though
//! it trips length>30). Two short interrogatives trip subord>=2
//! (`Who had darted...`, `That is as it happens`) — honest
//! threshold overfire, kept deliberately. Inputs whitespace-
//! normalized (harvest joins wrapped lines; hyphenation edge
//! accepted).
//!
//! Miss arbitration 2026-10-07 (6 FP, 0 FN — gold stands throughout):
//! 4× interrogative/comparative subord-counting quirks (short
//! questions read s>=2); 1× honest length overfire (p259s2, judged
//! fine at 31 words); 1× for-NP over-segmentation (p1908s0: grammar
//! splits purpose-`for` from NP-`for` identically — Tier-3 can't
//! tell them apart, the lint rule inherits it).
//!
//! Bars (pre-registered): precision >= 0.80, recall >= 0.65.
//! Grammar-only + vendored tagger: runs everywhere, no Tier-1 assets
//! (shallow path — see `annotate_shallow`).

use english_lint::{ClauseComplexity, Rule, SentenceLength};

// (sentence, is_complex_or_long).
#[rustfmt::skip]
const SENTENCES: &[(&str, bool)] = &[
    ("Though in many natural objects, whiteness refiningly enhances beauty, as if imparting some special virtue of its own, as in marbles, japonicas, and pearls; and though various nations have in some way recognised a certain royal preeminence in this hue; even the barbaric, grand old kings of Pegu placing the title “Lord of the White Elephants” above all their other magniloquent ascriptions of dominion; and the modern kings of Siam unfurling the same snow-white quadruped in the royal standard; and the Hanoverian flag bearing the one figure of a snow-white charger; and the great Austrian Empire, Cæsarian, heir to overlording Rome, having for the imperial colour the same imperial hue; and though this pre-eminence in it applies to the human race itself, giving the white man ideal mastership over every dusky tribe; and though, besides, all this, whiteness has been even made significant of gladness, for among the Romans a white stone marked a joyful day; and though in other mortal sympathies and symbolizings, this same hue is made the emblem of many touching, noble things—the innocence of brides, the benignity of age; though among the Red Men of America the giving of the white belt of wampum was the deepest pledge of honor; though in many climes, whiteness typifies the majesty of Justice in the ermine of the Judge, and contributes to the daily state of kings and queens drawn by milk-white steeds; though even in the higher mysteries of the most august religions it has been made the symbol of the divine spotlessness and power; by the Persian fire worshippers, the white forked flame being held the holiest on the altar; and in the Greek mythologies, Great Jove himself being made incarnate in a snow-white bull; and though to the noble Iroquois, the midwinter sacrifice of the sacred White Dog was by far the holiest festival of their theology, that spotless, faithful creature being held the purest envoy they could send to the Great Spirit with the annual tidings of their own fidelity; and though directly from the Latin word for white, all Christian priests derive the name of one part of their sacred vesture, the alb or tunic, worn beneath the cassock; and though among the holy pomps of the Romish faith, white is specially employed in the celebration of the Passion of our Lord; though in the Vision of St. John, white robes are given to the redeemed, and the four-and-twenty elders stand clothed in white before the great white throne, and the Holy One that sitteth there white like wool; yet for all these accumulated associations, with whatever is sweet, and honorable, and sublime, there yet lurks an elusive something in the innermost idea of this hue, which strikes more of panic to the soul than that redness which affrights in blood.", true),
    ("Until Cabaco’s published discovery, the sailors had little foreseen it, though to be sure when, after being a little while out of port, all hands had concluded the customary business of fitting the whaleboats for service; when some time after this Ahab was now and then found bestirring himself in the matter of making thole-pins with his own hands for what was thought to be one of the spare boats, and even solicitously cutting the small wooden skewers, which when the line is running out are pinned over the groove in the bow: when all this was observed in him, and particularly his solicitude in having an extra coat of sheathing in the bottom of the boat, as if to make it better withstand the pointed pressure of his ivory limb; and also the anxiety he evinced in exactly shaping the thigh board, or clumsy cleat, as it is sometimes called, the horizontal piece in the boat’s bow for bracing the knee against in darting or stabbing at the whale; when it was observed how often he stood up in that boat with his solitary knee fixed in the semi-circular depression in the cleat, and with the carpenter’s chisel gouged out a little here and straightened it a little there; all these things, I say, had awakened much interest and curiosity at the time.", true),
    ("Though amid all the smoking horror and diabolism of a sea-fight, sharks will be seen longingly gazing up to the ship’s decks, like hungry dogs round a table where red meat is being carved, ready to bolt down every killed man that is tossed to them; and though, while the valiant butchers over the deck-table are thus cannibally carving each other’s live meat with carving-knives all gilded and tasselled, the sharks, also, with their jewel-hilted mouths, are quarrelsomely carving away under the table at the dead meat; and though, were you to turn the whole affair upside down, it would still be pretty much the same thing, that is to say, a shocking sharkish business enough for all parties; and though sharks also are the invariable outriders of all slave ships crossing the Atlantic, systematically trotting alongside, to be handy in case a parcel is to be carried anywhere, or a dead slave to be decently buried; and though one or two other like instances might be set down, touching the set terms, places, and occasions, when sharks do most socially congregate, and most hilariously feast; yet is there no conceivable time or occasion when you will find them in such countless numbers, and in gayer or more jovial spirits, than around a dead sperm whale, moored by night to a whaleship at sea.", true),
    ("They contain round archipelagoes of romantic isles, even as the Polynesian waters do; in large part, are shored by two great contrasting nations, as the Atlantic is; they furnish long maritime approaches to our numerous territorial colonies from the East, dotted all round their banks; here and there are frowned upon by batteries, and by the goat-like craggy guns of lofty Mackinaw; they have heard the fleet thunderings of naval victories; at intervals, they yield their beaches to wild barbarians, whose red painted faces flash from out their peltry wigwams; for leagues and leagues are flanked by ancient and unentered forests, where the gaunt pines stand like serried lines of kings in Gothic genealogies; those same woods harboring wild Afric beasts of prey, and silken creatures whose exported furs give robes to Tartar Emperors; they mirror the paved capitals of Buffalo and Cleveland, as well as Winnebago villages; they float alike the full-rigged merchant ship, the armed cruiser of the State, the steamer, and the beech canoe; they are swept by Borean and dismasting blasts as direful as any that lash the salted wave; they know what shipwrecks are, for out of sight of land, however inland, they have drowned full many a midnight ship with all its shrieking crew.", true),
    ("For loath to depart, yet; very loath to leave, for good, a ship bound on so long and perilous a voyage—beyond both stormy Capes; a ship in which some thousands of his hard earned dollars were invested; a ship, in which an old shipmate sailed as captain; a man almost as old as he, once more starting to encounter all the terrors of the pitiless jaw; loath to say good-bye to a thing so every way brimful of every interest to him,—poor old Bildad lingered long; paced the deck with anxious strides; ran down into the cabin to speak another farewell word there; again came on deck, and looked to windward; looked towards the wide and endless waters, only bounded by the far-off unseen Eastern Continents; looked towards the land; looked aloft; looked right and left; looked everywhere and nowhere; and at last, mechanically coiling a rope upon its pin, convulsively grasped stout Peleg by the hand, and holding up a lantern, for a moment stood gazing heroically in his face, as much as to say, “Nevertheless, friend Peleg, I can stand it; yes, I can.”", true),
    ("Now, it was plainly a labor of love for Captain Sleet to describe, as he does, all the little detailed conveniences of his crow’s-nest; but though he so enlarges upon many of these, and though he treats us to a very scientific account of his experiments in this crow’s-nest, with a small compass he kept there for the purpose of counteracting the errors resulting from what is called the “local attraction” of all binnacle magnets; an error ascribable to the horizontal vicinity of the iron in the ship’s planks, and in the Glacier’s case, perhaps, to there having been so many broken-down blacksmiths among her crew; I say, that though the Captain is very discreet and scientific here, yet, for all his learned “binnacle deviations,” “azimuth compass observations,” and “approximate errors,” he knows very well, Captain Sleet, that he was not so much immersed in those profound magnetic meditations, as to fail being attracted occasionally towards that well replenished little case-bottle, so nicely tucked in on one side of his crow’s nest, within easy reach of his hand.", true),
    ("And when we consider that other theory of the natural philosophers, that all other earthly hues—every stately or lovely emblazoning—the sweet tinges of sunset skies and woods; yea, and the gilded velvets of butterflies, and the butterfly cheeks of young girls; all these are but subtile deceits, not actually inherent in substances, but only laid on from without; so that all deified Nature absolutely paints like the harlot, whose allurements cover nothing but the charnel-house within; and when we proceed further, and consider that the mystical cosmetic which produces every one of her hues, the great principle of light, for ever remains white or colorless in itself, and if operating without medium upon matter, would touch all objects, even tulips and roses, with its own blank tinge—pondering all this, the palsied universe lies before us a leper; and like wilful travellers in Lapland, who refuse to wear coloured and colouring glasses upon their eyes, so the wretched infidel gazes himself blind at the monumental white shroud that wraps all the prospect around him.", true),
    ("Considering, therefore, that squalls and capsizings in the water and consequent bivouacks on the deep, were matters of common occurrence in this kind of life; considering that at the superlatively critical instant of going on to the whale I must resign my life into the hands of him who steered the boat—oftentimes a fellow who at that very moment is in his impetuousness upon the point of scuttling the craft with his own frantic stampings; considering that the particular disaster to our own particular boat was chiefly to be imputed to Starbuck’s driving on to his whale almost in the teeth of a squall, and considering that Starbuck, notwithstanding, was famous for his great heedfulness in the fishery; considering that I belonged to this uncommonly prudent Starbuck’s boat; and finally considering in what a devil’s chase I was implicated, touching the White Whale: taking all things together, I say, I thought I might as well go below and make a rough draft of my will. “", true),
    ("As I sat there at my ease, cross-legged on the deck; after the bitter exertion at the windlass; under a blue tranquil sky; the ship under indolent sail, and gliding so serenely along; as I bathed my hands among those soft, gentle globules of infiltrated tissues, woven almost within the hour; as they richly broke to my fingers, and discharged all their opulence, like fully ripe grapes their wine; as I snuffed up that uncontaminated aroma,—literally and truly, like the smell of spring violets; I declare to you, that for the time I lived as in a musky meadow; I forgot all about our horrible oath; in that inexpressible sperm, I washed my hands and my heart of it; I almost began to credit the old Paracelsan superstition that sperm is of rare virtue in allaying the heat of anger; while bathing in that bath, I felt divinely free from all ill-will, or petulance, or malice, of any sort whatsoever.", true),
    ("But though, to landsmen in general, the native inhabitants of the seas have ever been regarded with emotions unspeakably unsocial and repelling; though we know the sea to be an everlasting terra incognita, so that Columbus sailed over numberless unknown worlds to discover his one superficial western one; though, by vast odds, the most terrific of all mortal disasters have immemorially and indiscriminately befallen tens and hundreds of thousands of those who have gone upon the waters; though but a moment’s consideration will teach, that however baby man may brag of his science and skill, and however much, in a flattering future, that science and skill may augment; yet for ever and for ever, to the crack of doom, the sea will insult and murder him, and pulverize the stateliest, stiffest frigate he can make; nevertheless, by the continual repetition of these very impressions, man has lost that sense of the full awfulness of the sea which aboriginally belongs to it.", true),
    ("Already has it been related how the great leviathan is afar off descried from the mast-head; how he is chased over the watery moors, and slaughtered in the valleys of the deep; how he is then towed alongside and beheaded; and how (on the principle which entitled the headsman of old to the garments in which the beheaded was killed) his great padded surtout becomes the property of his executioner; how, in due time, he is condemned to the pots, and, like Shadrach, Meshach, and Abednego, his spermaceti, oil, and bone pass unscathed through the fire;—but now it remains to conclude the last chapter of this part of the description by rehearsing—singing, if I may—the romantic proceeding of decanting off his oil into the casks and striking them down into the hold, where once again leviathan returns to his native profundities, sliding along beneath the surface as before; but, alas!", true),
    ("While the two crews were yet circling in the waters, reaching out after the revolving line-tubs, oars, and other floating furniture, while aslope little Flask bobbed up and down like an empty vial, twitching his legs upwards to escape the dreaded jaws of sharks; and Stubb was lustily singing out for some one to ladle him up; and while the old man’s line—now parting—admitted of his pulling into the creamy pool to rescue whom he could;—in that wild simultaneousness of a thousand concreted perils,—Ahab’s yet unstricken boat seemed drawn up towards Heaven by invisible wires,—as, arrow-like, shooting perpendicularly from the sea, the White Whale dashed his broad forehead against its bottom, and sent it, turning over and over, into the air; till it fell again—gunwale downwards—and Ahab and his men struggled out from under it, like seals from a sea-side cave.", true),
    ("Nor, at any time, by night or day could the mariners now step upon the deck, unless Ahab was before them; either standing in his pivot-hole, or exactly pacing the planks between two undeviating limits,—the main-mast and the mizen; or else they saw him standing in the cabin-scuttle,—his living foot advanced upon the deck, as if to step; his hat slouched heavily over his eyes; so that however motionless he stood, however the days and nights were added on, that he had not swung in his hammock; yet hidden beneath that slouching hat, they could never tell unerringly whether, for all this, his eyes were really closed at times; or whether he was still intently scanning them; no matter, though he stood so in the scuttle for a whole hour on the stretch, and the unheeded night-damp gathered in beads of dew upon that stone-carved coat and hat.", true),
    ("In what census of living creatures, the dead of mankind are included; why it is that a universal proverb says of them, that they tell no tales, though containing more secrets than the Goodwin Sands; how it is that to his name who yesterday departed for the other world, we prefix so significant and infidel a word, and yet do not thus entitle him, if he but embarks for the remotest Indies of this living earth; why the Life Insurance Companies pay death-forfeitures upon immortals; in what eternal, unstirring paralysis, and deadly, hopeless trance, yet lies antique Adam who died sixty round centuries ago; how it is that we still refuse to be comforted for those who we nevertheless maintain are dwelling in unspeakable bliss; why all the living so strive to hush all the dead; wherefore but the rumor of a knocking in a tomb will terrify a whole city.", true),
    ("He called one to him in the grey morning watch, when the day was just breaking, and taking his hand, said that while in Nantucket he had chanced to see certain little canoes of dark wood, like the rich war-wood of his native isle; and upon inquiry, he had learned that all whalemen who died in Nantucket, were laid in those same dark canoes, and that the fancy of being so laid had much pleased him; for it was not unlike the custom of his own race, who, after embalming a dead warrior, stretched him out in his canoe, and so left him to be floated away to the starry archipelagoes; for not only do they believe that the stars are isles, but that far beyond all visible horizons, their own mild, uncontinented seas, interflow with the blue heavens; and so form the white breakers of the milky way.", true),
    ("Every lingering struggle in his favour grew fainter and fainter; and in further justification of Mr. Darcy, she could not but allow that Mr. Bingley, when questioned by Jane, had long ago asserted his blamelessness in the affair;--that, proud and repulsive as were his manners, she had never, in the whole course of their acquaintance--an acquaintance which had latterly brought them much together, and given her a sort of intimacy with his ways--seen anything that betrayed him to be unprincipled or unjust--anything that spoke him of irreligious or immoral habits;--that among his own connections he was esteemed and valued;--that even Wickham had allowed him merit as a brother, and that she had often heard him speak so affectionately of his sister as to prove him capable of some amiable feeling;--that had his actions been what Wickham represented them, so gross a violation of everything right could hardly have been concealed from the world; and that friendship between a person capable of it and such an amiable man as Mr. Bingley was incomprehensible.", true),
    ("When this information was given, and they had all taken their seats, Mr. Collins was at leisure to look around him and admire, and he was so much struck with the size and furniture of the apartment, that he declared he might almost have supposed himself in the small summer breakfast parlour at Rosings; a comparison that did not at first convey much gratification; but when Mrs. Philips understood from him what Rosings was, and who was its proprietor, when she had listened to the description of only one of Lady Catherine’s drawing-rooms, and found that the chimney-piece alone had cost eight hundred pounds, she felt all the force of the compliment, and would hardly have resented a comparison with the housekeeper’s room.", true),
    ("After discharging his conscience on that head, he proceeded to inform them, with many rapturous expressions, of his happiness in having obtained the affection of their amiable neighbour, Miss Lucas, and then explained that it was merely with the view of enjoying her society that he had been so ready to close with their kind wish of seeing him again at Longbourn, whither he hoped to be able to return on Monday fortnight; for Lady Catherine, he added, so heartily approved his marriage, that she wished it to take place as soon as possible, which he trusted would be an unanswerable argument with his amiable Charlotte to name an early day for making him the happiest of men.", true),
    ("His present pursuit could not make him forget that Elizabeth had been the first to excite and to deserve his attention, the first to listen and to pity, the first to be admired; and in his manner of bidding her adieu, wishing her every enjoyment, reminding her of what she was to expect in Lady Catherine de Bourgh, and trusting their opinion of her--their opinion of everybody--would always coincide, there was a solicitude, an interest, which she felt must ever attach her to him with a most sincere regard; and she parted from him convinced, that, whether married or single, he must always be her model of the amiable and pleasing.", true),
    ("Elizabeth had heard, soon after her arrival, that Mr. Darcy was expected there in the course of a few weeks; and though there were not many of her acquaintance whom she did not prefer, his coming would furnish one comparatively new to look at in their Rosings parties, and she might be amused in seeing how hopeless Miss Bingley’s designs on him were, by his behaviour to his cousin, for whom he was evidently destined by Lady Catherine, who talked of his coming with the greatest satisfaction, spoke of him in terms of the highest admiration, and seemed almost angry to find that he had already been frequently seen by Miss Lucas and herself.", true),
    ("Those to her mother contained little else than that they were just returned from the library, where such and such officers had attended them, and where she had seen such beautiful ornaments as made her quite wild; that she had a new gown, or a new parasol, which she would have described more fully, but was obliged to leave off in a violent hurry, as Mrs. Forster called her, and they were going to the camp; and from her correspondence with her sister there was still less to be learnt, for her letters to Kitty, though rather longer, were much too full of lines under the words to be made public.", true),
    ("Their party in the dining-room was large, for almost all the Lucases came to meet Maria and hear the news; and various were the subjects which occupied them: Lady Lucas was inquiring of Maria, across the table, after the welfare and poultry of her eldest daughter; Mrs. Bennet was doubly engaged, on one hand collecting an account of the present fashions from Jane, who sat some way below her, and on the other, retailing them all to the younger Miss Lucases; and Lydia, in a voice rather louder than any other person’s, was enumerating the various pleasures of the morning to anybody who would hear her.", true),
    ("About a year ago, she was taken from school, and an establishment formed for her in London; and last summer she went with the lady who presided over it to Ramsgate; and thither also went Mr. Wickham, undoubtedly by design; for there proved to have been a prior acquaintance between him and Mrs. Younge, in whose character we were most unhappily deceived; and by her connivance and aid he so far recommended himself to Georgiana, whose affectionate heart retained a strong impression of his kindness to her as a child, that she was persuaded to believe herself in love and to consent to an elopement.", true),
    ("“I am by no means of opinion, I assure you,” said he, “that a ball of this kind, given by a young man of character, to respectable people, can have any evil tendency; and I am so far from objecting to dancing myself, that I shall hope to be honoured with the hands of all my fair cousins in the course of the evening; and I take this opportunity of soliciting yours, Miss Elizabeth, for the two first dances especially; a preference which I trust my cousin Jane will attribute to the right cause, and not to any disrespect for her.”", true),
    ("Mrs. Philips was always glad to see her nieces; and the two eldest, from their recent absence, were particularly welcome; and she was eagerly expressing her surprise at their sudden return home, which, as their own carriage had not fetched them, she should have known nothing about, if she had not happened to see Mr. Jones’s shopboy in the street, who had told her that they were not to send any more draughts to Netherfield, because the Miss Bennets were come away, when her civility was claimed towards Mr. Collins by Jane’s introduction of him.", true),
    ("“That is as it happens.", false),
    ("“As often as I can.", false),
    ("Tis as good as a lord!", false),
    ("“Such as vanity and pride.”", false),
    ("Her hair so untidy, so blowzy!”", false),
    ("I am so grieved for him.", false),
    ("“Not as you represent it.", false),
    ("They have at least that advantage.”", false),
    ("said Jane, as she finished it. “", false),
    ("it is just as he chooses.", false),
    ("She will follow wherever Lydia leads.", false),
    ("It was as follows:--", false),
    ("Indolence and idleness perished before him.", false),
    ("Starbuck paled, and turned, and shivered.", false),
    ("tis but resting for the rush.”", false),
    ("Who had darted that stone lance?", false),
    ("how that harmless question mangles Jonah!", false),
    ("Talk not that lingo to me.", false),
    ("“Who is Captain Ahab, sir?”", false),
    ("Was not that what ye said?", false),
    ("he must have more than that.”", false),
    ("But all remained still as before.", false),
    ("“All right again before long!”", false),
    ("Jane’s temper was not desponding; and she was gradually led to hope, though the diffidence of affection sometimes overcame the hope, that Bingley would return to Netherfield, and answer every wish of her heart.", true),
    ("Mary petitioned for the use of the library at Netherfield; and Kitty begged very hard for a few balls there every winter.", false),
    ("When coffee was over, Colonel Fitzwilliam reminded Elizabeth of having promised to play to him; and she sat down directly to the instrument.", false),
    ("In that county there was enough to be seen to occupy the chief of their three weeks; and to Mrs. Gardiner it had a peculiarly strong attraction.", false),
    ("Bingley was endeared to Darcy by the easiness, openness, and ductility of his temper, though no disposition could offer a greater contrast to his own, and though with his own he never appeared dissatisfied.", true),
    ("At length, however, Mrs. Bennet had no more to say; and Lady Lucas, who had been long yawning at the repetition of delights which she saw no likelihood of sharing, was left to the comforts of cold ham and chicken.", true),
    ("She raised her veil as she spoke, and we could see that she was indeed in a pitiable state of agitation, her face all drawn and grey, with restless frightened eyes, like those of some hunted animal.", true),
    ("The only point which I could not quite understand was what use you could make of a hydraulic press in excavating fuller’s-earth, which, as I understand, is dug out like gravel from a pit.’", true),
    ("There was a street on each side and an open door on both, which made the large, low room pretty clear to see in, in spite of clouds of tobacco smoke.", false),
    ("She would not, she declared, lose money that belonged to her fatherless boy; “If none of the rest of you dare,” she said, “Jim and I dare.", true),
    ("These fellows who attacked the inn tonight--bold, desperate blades, for sure--and the rest who stayed aboard that lugger, and more, I dare say, not far off, are, one and all, through thick and thin, bound that they’ll get that money.", true),
    ("I found he was an old sailor, kept a public-house, knew all the seafaring men in Bristol, had lost his health ashore, and wanted a good berth as cook to get to sea again.", true),
];

/// Shallow pipeline per sentence (grammar + vendored tagger only —
/// these rules never touch the parser, so this eval runs everywhere
/// with no Tier-1 assets).
fn annotate_shallow_all(text: &str) -> english_lint::AnnotatedDoc {
    let tagger =
        english_pos::Model::from_json(include_str!("../../english-pos/weights/upos.json")).unwrap();
    english_lint::annotate_shallow(&tagger, text)
}

#[test]
fn complexity_precision_recall() {
    assert_eq!(SENTENCES.len(), 60);
    let length = SentenceLength::default();
    let complexity = ClauseComplexity::default();
    let rules: Vec<&dyn Rule> = vec![&length, &complexity];
    let (mut tp, mut fp, mut tn, mut fn_) = (0usize, 0usize, 0usize, 0usize);
    let mut misses = Vec::new();
    for (si, (text, gold)) in SENTENCES.iter().enumerate() {
        let doc = annotate_shallow_all(text);
        let mut fired = false;
        for rule in &rules {
            if !rule.check(&doc).is_empty() {
                fired = true;
                break;
            }
        }
        match (fired, gold) {
            (true, true) => tp += 1,
            (true, false) => {
                fp += 1;
                misses.push(format!("FP#{si}: {text}"));
            }
            (false, false) => tn += 1,
            (false, true) => {
                fn_ += 1;
                misses.push(format!("FN#{si}: {text}"));
            }
        }
    }
    let precision = tp as f64 / (tp + fp).max(1) as f64;
    let recall = tp as f64 / (tp + fn_).max(1) as f64;
    eprintln!(
        "complexity eval: tp={tp} fp={fp} tn={tn} fn={fn_} precision={precision:.3} recall={recall:.3}\nmisses: {misses:?}"
    );
    assert!(
        precision >= 0.80,
        "complexity precision {precision:.3} below pre-registered bar; investigate, do not lower",
    );
    assert!(
        recall >= 0.65,
        "complexity recall {recall:.3} below pre-registered bar; investigate, do not lower",
    );
}
