//! Hard-prose tag eval: 10 hand-tagged Moby-Dick sentences picked by
//! the `candidates` uncertainty ranker (low margins, beam diffs,
//! that-cascades, s-nouns, titlecase, coordination, subordination),
//! disjoint from `moby.rs`, `genre.rs`, and all oracle batches.
//! UD-style tokens (punctuation split, contractions split, ASCII
//! apostrophes), EWT-side conventions per CANONICAL.md.
//!
//! Deliberate gold calls (EWT counts checked, guideline overridden
//! only by majority): `such`→ADJ 72:24; `other`→ADJ 268:1;
//! `as`+pronoun→SCONJ 78:0; `as a`→ADP 106:1; `as-X-as`
//! first→ADV (74 ADV-first + 49 ADV-first, unanimous) incl. `as
//! much as`; clausal second-`as`→SCONJ; `at all`→ADP+DET 27:0; `but`+ADJ→CCONJ 87:0;
//! `each other`→DET+ADJ 15:0; `one`+NOUN→NUM 133:3;
//! `because of`→ADP+ADP 39:3; `going to`→VERB 182:0;
//! `preceding`→ADJ 6:0 (postpositive reduced relatives stay VERB:
//! `thrown`, `employed`, `made`); `hidden`→ADJ 6:2 (predicative,
//! like `concerned`); existentials→PRON+VERB; possessives→PRON;
//! subjunctive/base `pluck`→VERB; archaic `saith`/`ye`/`aye`,
//! `twain`→NUM, generic-plural `Senators`/`Crappoes`→NOUN (M1),
//! personified agents (`Death`, `Nature`, `Fates`)→PROPN,
//! `here's`→ADV+VERB (existential), `won't`→AUX+PART,
//! attributive participles→ADJ, passive/progressive/perfect
//! participles→VERB. Authoring method: WORD+TAG lines feed a
//! generator (pairs can't misalign — the parallel-array failure
//! mode caught in review); every model-disagreement individually
//! justified above or fixed. Bar set from measurement (below).
//!
//! Text is original Moby-Dick (public domain, Melville d. 1891).

use english_pos::Model;

const TOKENS4: &[&str] = &[
    "And",
    "when",
    "we",
    "consider",
    "that",
    "other",
    "theory",
    "of",
    "the",
    "natural",
    "philosophers",
    ",",
    "that",
    "all",
    "other",
    "earthly",
    "hues",
    "—",
    "every",
    "stately",
    "or",
    "lovely",
    "emblazoning",
    "—",
    "the",
    "sweet",
    "tinges",
    "of",
    "sunset",
    "skies",
    "and",
    "woods",
    ";",
    "yea",
    "and",
    "the",
    "gilded",
    "velvets",
    "of",
    "butterflies",
    "and",
    "the",
    "butterfly",
    "cheeks",
    "of",
    "young",
    "girls",
    ";",
    "all",
    "these",
    "are",
    "but",
    "subtile",
    "deceits",
    ",",
    "not",
    "actually",
    "inherent",
    "in",
    "substances",
    ",",
    "but",
    "only",
    "laid",
    "on",
    "from",
    "without",
    ";",
    "so",
    "that",
    "all",
    "deified",
    "Nature",
    "absolutely",
    "paints",
    "like",
    "the",
    "harlot",
    ",",
    "whose",
    "allurements",
    "cover",
    "nothing",
    "but",
    "the",
    "charnel-house",
    "within",
    ";",
    "and",
    "when",
    "we",
    "proceed",
    "further",
    "and",
    "consider",
    "that",
    "the",
    "mystical",
    "cosmetic",
    "which",
    "produces",
    "every",
    "one",
    "of",
    "her",
    "hues",
    ",",
    "the",
    "great",
    "principle",
    "of",
    "light",
    ",",
    "for",
    "ever",
    "remains",
    "white",
    "or",
    "colorless",
    "in",
    "itself",
    ",",
    "and",
    "if",
    "operating",
    "without",
    "medium",
    "upon",
    "matter",
    ",",
    "would",
    "touch",
    "all",
    "objects",
    ",",
    "even",
    "tulips",
    "and",
    "roses",
    ",",
    "with",
    "its",
    "own",
    "blank",
    "tinge",
    "—",
    "pondering",
    "all",
    "this",
    ",",
    "the",
    "palsied",
    "universe",
    "lies",
    "before",
    "us",
    "a",
    "leper",
    ";",
    "and",
    "like",
    "wilful",
    "travellers",
    "in",
    "Lapland",
    ",",
    "who",
    "refuse",
    "to",
    "wear",
    "coloured",
    "and",
    "colouring",
    "glasses",
    "upon",
    "their",
    "eyes",
    ",",
    "so",
    "the",
    "wretched",
    "infidel",
    "gazes",
    "himself",
    "blind",
    "at",
    "the",
    "monumental",
    "white",
    "shroud",
    "that",
    "wraps",
    "all",
    "the",
    "prospect",
    "around",
    "him",
    ".", //
    "If",
    "two",
    "strangers",
    "crossing",
    "the",
    "Pine",
    "Barrens",
    "in",
    "New",
    "York",
    "State",
    "or",
    "the",
    "equally",
    "desolate",
    "Salisbury",
    "Plain",
    "in",
    "England",
    ";",
    "if",
    "casually",
    "encountering",
    "each",
    "other",
    "in",
    "such",
    "inhospitable",
    "wilds",
    ",",
    "these",
    "twain",
    ",",
    "for",
    "the",
    "life",
    "of",
    "them",
    ",",
    "can",
    "not",
    "well",
    "avoid",
    "a",
    "mutual",
    "salutation",
    ";",
    "and",
    "stopping",
    "for",
    "a",
    "moment",
    "to",
    "interchange",
    "the",
    "news",
    ";",
    "and",
    ",",
    "perhaps",
    ",",
    "sitting",
    "down",
    "for",
    "a",
    "while",
    "and",
    "resting",
    "in",
    "concert",
    ":",
    "then",
    ",",
    "how",
    "much",
    "more",
    "natural",
    "that",
    "upon",
    "the",
    "illimitable",
    "Pine",
    "Barrens",
    "and",
    "Salisbury",
    "Plains",
    "of",
    "the",
    "sea",
    ",",
    "two",
    "whaling",
    "vessels",
    "descrying",
    "each",
    "other",
    "at",
    "the",
    "ends",
    "of",
    "the",
    "earth",
    "—",
    "off",
    "lone",
    "Fanning",
    "'s",
    "Island",
    ",",
    "or",
    "the",
    "far",
    "away",
    "King",
    "'s",
    "Mills",
    ";",
    "how",
    "much",
    "more",
    "natural",
    ",",
    "I",
    "say",
    ",",
    "that",
    "under",
    "such",
    "circumstances",
    "these",
    "ships",
    "should",
    "not",
    "only",
    "interchange",
    "hails",
    ",",
    "but",
    "come",
    "into",
    "still",
    "closer",
    ",",
    "more",
    "friendly",
    "and",
    "sociable",
    "contact",
    ".", //
    "I",
    "well",
    "know",
    "that",
    "these",
    "Crappoes",
    "of",
    "Frenchmen",
    "are",
    "but",
    "poor",
    "devils",
    "in",
    "the",
    "fishery",
    ";",
    "sometimes",
    "lowering",
    "their",
    "boats",
    "for",
    "breakers",
    ",",
    "mistaking",
    "them",
    "for",
    "Sperm",
    "Whale",
    "spouts",
    ";",
    "yes",
    "and",
    "sometimes",
    "sailing",
    "from",
    "their",
    "port",
    "with",
    "their",
    "hold",
    "full",
    "of",
    "boxes",
    "of",
    "tallow",
    "candles",
    "and",
    "cases",
    "of",
    "snuffers",
    ",",
    "foreseeing",
    "that",
    "all",
    "the",
    "oil",
    "they",
    "will",
    "get",
    "wo",
    "n't",
    "be",
    "enough",
    "to",
    "dip",
    "the",
    "Captain",
    "'s",
    "wick",
    "into",
    ";",
    "aye",
    ",",
    "we",
    "all",
    "know",
    "these",
    "things",
    ";",
    "but",
    "look",
    "ye",
    ",",
    "here",
    "'s",
    "a",
    "Crappo",
    "that",
    "is",
    "content",
    "with",
    "our",
    "leavings",
    ",",
    "the",
    "drugged",
    "whale",
    "there",
    ",",
    "I",
    "mean",
    ";",
    "aye",
    ",",
    "and",
    "is",
    "content",
    "too",
    "with",
    "scraping",
    "the",
    "dry",
    "bones",
    "of",
    "that",
    "other",
    "precious",
    "fish",
    "he",
    "has",
    "there",
    ".", //
    "But",
    "I",
    "am",
    "going",
    "now",
    "to",
    "keep",
    "a",
    "sharp",
    "look-out",
    "on",
    "him",
    ";",
    "and",
    "if",
    "I",
    "see",
    "anything",
    "very",
    "suspicious",
    "going",
    "on",
    ",",
    "I",
    "'ll",
    "just",
    "take",
    "him",
    "by",
    "the",
    "nape",
    "of",
    "his",
    "neck",
    ",",
    "and",
    "say",
    "—",
    "Look",
    "here",
    ",",
    "Beelzebub",
    ",",
    "you",
    "do",
    "n't",
    "do",
    "it",
    ";",
    "and",
    "if",
    "he",
    "makes",
    "any",
    "fuss",
    ",",
    "by",
    "the",
    "Lord",
    "I",
    "'ll",
    "make",
    "a",
    "grab",
    "into",
    "his",
    "pocket",
    "for",
    "his",
    "tail",
    ",",
    "take",
    "it",
    "to",
    "the",
    "capstan",
    ",",
    "and",
    "give",
    "him",
    "such",
    "a",
    "wrenching",
    "and",
    "heaving",
    ",",
    "that",
    "his",
    "tail",
    "will",
    "come",
    "short",
    "off",
    "at",
    "the",
    "stump",
    "—",
    "do",
    "you",
    "see",
    ";",
    "and",
    "then",
    ",",
    "I",
    "rather",
    "guess",
    "when",
    "he",
    "finds",
    "himself",
    "docked",
    "in",
    "that",
    "queer",
    "fashion",
    ",",
    "he",
    "'ll",
    "sneak",
    "off",
    "without",
    "the",
    "poor",
    "satisfaction",
    "of",
    "feeling",
    "his",
    "tail",
    "between",
    "his",
    "legs",
    ".", //
    "That",
    "part",
    "of",
    "the",
    "sea",
    "known",
    "among",
    "whalemen",
    "as",
    "the",
    "\"",
    "Brazil",
    "Banks",
    "\"",
    "does",
    "not",
    "bear",
    "that",
    "name",
    "as",
    "the",
    "Banks",
    "of",
    "Newfoundland",
    "do",
    ",",
    "because",
    "of",
    "there",
    "being",
    "shallows",
    "and",
    "soundings",
    "there",
    ",",
    "but",
    "because",
    "of",
    "this",
    "remarkable",
    "meadow-like",
    "appearance",
    ",",
    "caused",
    "by",
    "the",
    "vast",
    "drifts",
    "of",
    "brit",
    "continually",
    "floating",
    "in",
    "those",
    "latitudes",
    ",",
    "where",
    "the",
    "Right",
    "Whale",
    "is",
    "often",
    "chased",
    ".", //
    "Already",
    "has",
    "it",
    "been",
    "related",
    "how",
    "the",
    "great",
    "leviathan",
    "is",
    "afar",
    "off",
    "descried",
    "from",
    "the",
    "mast-head",
    ";",
    "how",
    "he",
    "is",
    "chased",
    "over",
    "the",
    "watery",
    "moors",
    ",",
    "and",
    "slaughtered",
    "in",
    "the",
    "valleys",
    "of",
    "the",
    "deep",
    ";",
    "how",
    "he",
    "is",
    "then",
    "towed",
    "alongside",
    "and",
    "beheaded",
    ";",
    "and",
    "how",
    "(",
    "on",
    "the",
    "principle",
    "which",
    "entitled",
    "the",
    "headsman",
    "of",
    "old",
    "to",
    "the",
    "garments",
    "in",
    "which",
    "the",
    "beheaded",
    "was",
    "killed",
    ",",
    "his",
    "great",
    "padded",
    "surtout",
    "becomes",
    "the",
    "property",
    "of",
    "his",
    "executioner",
    ";",
    "how",
    ",",
    "in",
    "due",
    "time",
    ",",
    "he",
    "is",
    "condemned",
    "to",
    "the",
    "pots",
    ",",
    "and",
    ",",
    "like",
    "Shadrach",
    ",",
    "Meshach",
    ",",
    "and",
    "Abednego",
    ",",
    "his",
    "spermaceti",
    ",",
    "oil",
    ",",
    "and",
    "bone",
    "pass",
    "unscathed",
    "through",
    "the",
    "fire",
    ";",
    "—",
    "but",
    "now",
    "it",
    "remains",
    "to",
    "conclude",
    "the",
    "last",
    "chapter",
    "of",
    "this",
    "part",
    "of",
    "the",
    "description",
    "by",
    "rehearsing",
    "—",
    "singing",
    ",",
    "if",
    "I",
    "may",
    "—",
    "the",
    "romantic",
    "proceeding",
    "of",
    "decanting",
    "off",
    "his",
    "oil",
    "into",
    "the",
    "casks",
    "and",
    "striking",
    "them",
    "down",
    "into",
    "the",
    "hold",
    ",",
    "where",
    "once",
    "again",
    "leviathan",
    "returns",
    "to",
    "his",
    "native",
    "profundities",
    ",",
    "sliding",
    "along",
    "beneath",
    "the",
    "surface",
    "as",
    "before",
    ";",
    "but",
    ",",
    "alas",
    "!", //
    "Some",
    "gamesome",
    "wights",
    "will",
    "tell",
    "you",
    "that",
    "they",
    "have",
    "to",
    "plant",
    "weeds",
    "there",
    ",",
    "they",
    "do",
    "n't",
    "grow",
    "naturally",
    ";",
    "that",
    "they",
    "import",
    "Canada",
    "thistles",
    ";",
    "that",
    "they",
    "have",
    "to",
    "send",
    "beyond",
    "seas",
    "for",
    "a",
    "spile",
    "to",
    "stop",
    "a",
    "leak",
    "in",
    "an",
    "oil",
    "cask",
    ";",
    "that",
    "pieces",
    "of",
    "wood",
    "in",
    "Nantucket",
    "are",
    "carried",
    "about",
    "like",
    "bits",
    "of",
    "the",
    "true",
    "cross",
    "in",
    "Rome",
    ";",
    "that",
    "people",
    "there",
    "plant",
    "toadstools",
    "before",
    "their",
    "houses",
    ",",
    "to",
    "get",
    "under",
    "the",
    "shade",
    "in",
    "summer",
    "time",
    ";",
    "that",
    "one",
    "blade",
    "of",
    "grass",
    "makes",
    "an",
    "oasis",
    ",",
    "three",
    "blades",
    "in",
    "a",
    "day",
    "'s",
    "walk",
    "a",
    "prairie",
    ";",
    "that",
    "they",
    "wear",
    "quicksand",
    "shoes",
    ",",
    "something",
    "like",
    "Laplander",
    "snow-shoes",
    ";",
    "that",
    "they",
    "are",
    "so",
    "shut",
    "up",
    ",",
    "belted",
    ",",
    "about",
    ",",
    "every",
    "way",
    "inclosed",
    "surrounded",
    ",",
    "and",
    "made",
    "an",
    "utter",
    "island",
    "of",
    "by",
    "the",
    "ocean",
    ",",
    "that",
    "to",
    "their",
    "very",
    "chairs",
    "and",
    "tables",
    "small",
    "clams",
    "will",
    "sometimes",
    "be",
    "found",
    "adhering",
    ",",
    "as",
    "to",
    "the",
    "backs",
    "of",
    "sea",
    "turtles",
    ".", //
    "And",
    "now",
    "that",
    "at",
    "the",
    "proper",
    "time",
    "and",
    "place",
    ",",
    "after",
    "so",
    "long",
    "and",
    "wide",
    "a",
    "preliminary",
    "cruise",
    ",",
    "Ahab",
    ",",
    "—",
    "all",
    "other",
    "whaling",
    "waters",
    "swept",
    "—",
    "seemed",
    "to",
    "have",
    "chased",
    "his",
    "foe",
    "into",
    "an",
    "ocean-fold",
    ",",
    "to",
    "slay",
    "him",
    "the",
    "more",
    "securely",
    "there",
    ";",
    "now",
    ",",
    "that",
    "he",
    "found",
    "himself",
    "hard",
    "by",
    "the",
    "very",
    "latitude",
    "and",
    "longitude",
    "where",
    "his",
    "tormenting",
    "wound",
    "had",
    "been",
    "inflicted",
    ";",
    "now",
    "that",
    "a",
    "vessel",
    "had",
    "been",
    "spoken",
    "which",
    "on",
    "the",
    "very",
    "day",
    "preceding",
    "had",
    "actually",
    "encountered",
    "Moby",
    "Dick",
    ";",
    "—",
    "and",
    "now",
    "that",
    "all",
    "his",
    "successive",
    "meetings",
    "with",
    "various",
    "ships",
    "contrastingly",
    "concurred",
    "to",
    "show",
    "the",
    "demoniac",
    "indifference",
    "with",
    "which",
    "the",
    "white",
    "whale",
    "tore",
    "his",
    "hunters",
    ",",
    "whether",
    "sinning",
    "or",
    "sinned",
    "against",
    ";",
    "now",
    "it",
    "was",
    "that",
    "there",
    "lurked",
    "a",
    "something",
    "in",
    "the",
    "old",
    "man",
    "'s",
    "eyes",
    ",",
    "which",
    "it",
    "was",
    "hardly",
    "sufferable",
    "for",
    "feeble",
    "souls",
    "to",
    "see",
    ".", //
    "Nor",
    ",",
    "at",
    "any",
    "time",
    ",",
    "by",
    "night",
    "or",
    "day",
    "could",
    "the",
    "mariners",
    "now",
    "step",
    "upon",
    "the",
    "deck",
    ",",
    "unless",
    "Ahab",
    "was",
    "before",
    "them",
    ";",
    "either",
    "standing",
    "in",
    "his",
    "pivot-hole",
    ",",
    "or",
    "exactly",
    "pacing",
    "the",
    "planks",
    "between",
    "two",
    "undeviating",
    "limits",
    ",",
    "—",
    "the",
    "main-mast",
    "and",
    "the",
    "mizen",
    ",",
    "—",
    "or",
    "else",
    "they",
    "saw",
    "him",
    "standing",
    "in",
    "the",
    "cabin-scuttle",
    ",",
    "—",
    "his",
    "living",
    "foot",
    "advanced",
    "upon",
    "the",
    "deck",
    ",",
    "as",
    "if",
    "to",
    "step",
    ";",
    "his",
    "hat",
    "slouched",
    "heavily",
    "over",
    "his",
    "eyes",
    ";",
    "so",
    "that",
    "however",
    "motionless",
    "he",
    "stood",
    ",",
    "however",
    "the",
    "days",
    "and",
    "nights",
    "were",
    "added",
    "on",
    ",",
    "that",
    "he",
    "had",
    "not",
    "swung",
    "in",
    "his",
    "hammock",
    ";",
    "yet",
    "hidden",
    "beneath",
    "that",
    "slouching",
    "hat",
    ",",
    "they",
    "could",
    "never",
    "tell",
    "unerringly",
    "whether",
    ",",
    "for",
    "all",
    "this",
    ",",
    "his",
    "eyes",
    "were",
    "really",
    "closed",
    "at",
    "times",
    ";",
    "or",
    "whether",
    "he",
    "was",
    "still",
    "intently",
    "scanning",
    ";",
    "no",
    "matter",
    ",",
    "though",
    "he",
    "stood",
    "so",
    "in",
    "the",
    "scuttle",
    "for",
    "a",
    "whole",
    "hour",
    "on",
    "the",
    "stretch",
    ",",
    "and",
    "the",
    "unheeded",
    "night-damp",
    "collected",
    "in",
    "beads",
    "of",
    "dew",
    "upon",
    "that",
    "stone-carved",
    "coat",
    "and",
    "hat",
    ".", //
    "For",
    "loath",
    "to",
    "depart",
    ",",
    "yet",
    ";",
    "very",
    "loath",
    "to",
    "leave",
    ",",
    "for",
    "good",
    ",",
    "a",
    "ship",
    "bound",
    "on",
    "so",
    "long",
    "and",
    "perilous",
    "a",
    "voyage",
    "—",
    "beyond",
    "both",
    "stormy",
    "Capes",
    ",",
    "a",
    "ship",
    "in",
    "which",
    "some",
    "thousands",
    "of",
    "his",
    "hard",
    "earned",
    "dollars",
    "were",
    "invested",
    ";",
    "a",
    "ship",
    ",",
    "in",
    "which",
    "an",
    "old",
    "shipmate",
    "sailed",
    "as",
    "captain",
    ",",
    "a",
    "man",
    "almost",
    "as",
    "old",
    "as",
    "he",
    ",",
    "once",
    "more",
    "starting",
    "to",
    "encounter",
    "all",
    "the",
    "terrors",
    "of",
    "the",
    "pitiless",
    "jaw",
    ";",
    "loath",
    "to",
    "say",
    "good-bye",
    "to",
    "a",
    "thing",
    "so",
    "every",
    "way",
    "brimful",
    "of",
    "every",
    "interest",
    "to",
    "him",
    ",",
    "—",
    "poor",
    "old",
    "Bildad",
    "lingered",
    "long",
    ";",
    "paced",
    "the",
    "deck",
    "with",
    "anxious",
    "strides",
    ";",
    "ran",
    "down",
    "into",
    "the",
    "cabin",
    "to",
    "speak",
    "another",
    "farewell",
    "word",
    "there",
    ";",
    "again",
    "came",
    "on",
    "deck",
    ",",
    "and",
    "looked",
    "to",
    "windward",
    ",",
    "looked",
    "towards",
    "the",
    "wide",
    "and",
    "endless",
    "waters",
    ",",
    "only",
    "bounded",
    "by",
    "the",
    "far-off",
    "unseen",
    "Eastern",
    "Continents",
    ";",
    "looked",
    "towards",
    "the",
    "land",
    ";",
    "looked",
    "aloft",
    ";",
    "looked",
    "right",
    "and",
    "left",
    ";",
    "looked",
    "everywhere",
    "and",
    "nowhere",
    ";",
    "and",
    "at",
    "last",
    ",",
    "mechanically",
    "coiling",
    "a",
    "rope",
    "upon",
    "its",
    "pin",
    ",",
    "convulsively",
    "grasped",
    "stout",
    "Peleg",
    "by",
    "the",
    "hand",
    ",",
    "and",
    "holding",
    "up",
    "a",
    "lantern",
    ",",
    "for",
    "a",
    "moment",
    "stood",
    "gazing",
    "heroically",
    "in",
    "his",
    "face",
    ",",
    "as",
    "much",
    "as",
    "to",
    "say",
    ",",
    "\"",
    "Nevertheless",
    ",",
    "friend",
    "Peleg",
    ",",
    "I",
    "can",
    "stand",
    "it",
    ";",
    "yes",
    ",",
    "I",
    "can",
    ".",
    "\"", //
];

const GOLD4: &[&str] = &[
    "CCONJ", "ADV", "PRON", "VERB", "SCONJ", "ADJ", "NOUN", "ADP", "DET", "ADJ", "NOUN", "PUNCT",
    "SCONJ", "DET", "ADJ", "ADJ", "NOUN", "PUNCT", "DET", "ADJ", "CCONJ", "ADJ", "NOUN", "PUNCT",
    "DET", "ADJ", "NOUN", "ADP", "NOUN", "NOUN", "CCONJ", "NOUN", "PUNCT", "INTJ", "CCONJ", "DET",
    "ADJ", "NOUN", "ADP", "NOUN", "CCONJ", "DET", "NOUN", "NOUN", "ADP", "ADJ", "NOUN", "PUNCT",
    "DET", "DET", "AUX", "CCONJ", "ADJ", "NOUN", "PUNCT", "PART", "ADV", "ADJ", "ADP", "NOUN",
    "PUNCT", "CCONJ", "ADV", "VERB", "ADP", "ADP", "ADV", "PUNCT", "SCONJ", "SCONJ", "DET", "ADJ",
    "PROPN", "ADV", "VERB", "ADP", "DET", "NOUN", "PUNCT", "PRON", "NOUN", "VERB", "PRON", "CCONJ",
    "DET", "NOUN", "ADV", "PUNCT", "CCONJ", "ADV", "PRON", "VERB", "ADV", "CCONJ", "VERB", "SCONJ",
    "DET", "ADJ", "NOUN", "PRON", "VERB", "DET", "PRON", "ADP", "PRON", "NOUN", "PUNCT", "DET",
    "ADJ", "NOUN", "ADP", "NOUN", "PUNCT", "ADP", "ADV", "VERB", "ADJ", "CCONJ", "ADJ", "ADP",
    "PRON", "PUNCT", "CCONJ", "SCONJ", "VERB", "ADP", "NOUN", "ADP", "NOUN", "PUNCT", "AUX",
    "VERB", "DET", "NOUN", "PUNCT", "ADV", "NOUN", "CCONJ", "NOUN", "PUNCT", "ADP", "PRON", "ADJ",
    "ADJ", "NOUN", "PUNCT", "VERB", "DET", "PRON", "PUNCT", "DET", "ADJ", "NOUN", "VERB", "ADP",
    "PRON", "DET", "NOUN", "PUNCT", "CCONJ", "ADP", "ADJ", "NOUN", "ADP", "PROPN", "PUNCT", "PRON",
    "VERB", "PART", "VERB", "ADJ", "CCONJ", "ADJ", "NOUN", "ADP", "PRON", "NOUN", "PUNCT", "ADV",
    "DET", "ADJ", "NOUN", "VERB", "PRON", "ADJ", "ADP", "DET", "ADJ", "ADJ", "NOUN", "PRON",
    "VERB", "DET", "DET", "NOUN", "ADP", "PRON", "PUNCT", //
    "SCONJ", "NUM", "NOUN", "VERB", "DET", "PROPN", "PROPN", "ADP", "PROPN", "PROPN", "PROPN",
    "CCONJ", "DET", "ADV", "ADJ", "PROPN", "PROPN", "ADP", "PROPN", "PUNCT", "SCONJ", "ADV",
    "VERB", "DET", "ADJ", "ADP", "ADJ", "ADJ", "NOUN", "PUNCT", "DET", "NUM", "PUNCT", "ADP",
    "DET", "NOUN", "ADP", "PRON", "PUNCT", "AUX", "PART", "ADV", "VERB", "DET", "ADJ", "NOUN",
    "PUNCT", "CCONJ", "VERB", "ADP", "DET", "NOUN", "PART", "VERB", "DET", "NOUN", "PUNCT",
    "CCONJ", "PUNCT", "ADV", "PUNCT", "VERB", "ADP", "ADP", "DET", "NOUN", "CCONJ", "VERB", "ADP",
    "NOUN", "PUNCT", "ADV", "PUNCT", "ADV", "ADV", "ADV", "ADJ", "SCONJ", "ADP", "DET", "ADJ",
    "PROPN", "PROPN", "CCONJ", "PROPN", "PROPN", "ADP", "DET", "NOUN", "PUNCT", "NUM", "NOUN",
    "NOUN", "VERB", "DET", "ADJ", "ADP", "DET", "NOUN", "ADP", "DET", "NOUN", "PUNCT", "ADV",
    "ADJ", "PROPN", "PART", "PROPN", "PUNCT", "CCONJ", "DET", "ADV", "ADV", "PROPN", "PART",
    "PROPN", "PUNCT", "ADV", "ADV", "ADV", "ADJ", "PUNCT", "PRON", "VERB", "PUNCT", "SCONJ", "ADP",
    "ADJ", "NOUN", "DET", "NOUN", "AUX", "PART", "ADV", "VERB", "NOUN", "PUNCT", "CCONJ", "VERB",
    "ADP", "ADV", "ADJ", "PUNCT", "ADV", "ADJ", "CCONJ", "ADJ", "NOUN", "PUNCT", //
    "PRON", "ADV", "VERB", "SCONJ", "DET", "NOUN", "ADP", "NOUN", "AUX", "CCONJ", "ADJ", "NOUN",
    "ADP", "DET", "NOUN", "PUNCT", "ADV", "VERB", "PRON", "NOUN", "ADP", "NOUN", "PUNCT", "VERB",
    "PRON", "ADP", "NOUN", "NOUN", "NOUN", "PUNCT", "INTJ", "CCONJ", "ADV", "VERB", "ADP", "PRON",
    "NOUN", "ADP", "PRON", "NOUN", "ADJ", "ADP", "NOUN", "ADP", "NOUN", "NOUN", "CCONJ", "NOUN",
    "ADP", "NOUN", "PUNCT", "VERB", "SCONJ", "DET", "DET", "NOUN", "PRON", "AUX", "VERB", "AUX",
    "PART", "AUX", "ADJ", "PART", "VERB", "DET", "PROPN", "PART", "NOUN", "ADP", "PUNCT", "INTJ",
    "PUNCT", "PRON", "DET", "VERB", "DET", "NOUN", "PUNCT", "CCONJ", "VERB", "PRON", "PUNCT",
    "ADV", "VERB", "DET", "NOUN", "PRON", "AUX", "ADJ", "ADP", "PRON", "NOUN", "PUNCT", "DET",
    "ADJ", "NOUN", "ADV", "PUNCT", "PRON", "VERB", "PUNCT", "INTJ", "PUNCT", "CCONJ", "AUX", "ADJ",
    "ADV", "ADP", "VERB", "DET", "ADJ", "NOUN", "ADP", "DET", "ADJ", "ADJ", "NOUN", "PRON", "VERB",
    "ADV", "PUNCT", //
    "CCONJ", "PRON", "AUX", "VERB", "ADV", "PART", "VERB", "DET", "ADJ", "NOUN", "ADP", "PRON",
    "PUNCT", "CCONJ", "SCONJ", "PRON", "VERB", "PRON", "ADV", "ADJ", "VERB", "ADP", "PUNCT",
    "PRON", "AUX", "ADV", "VERB", "PRON", "ADP", "DET", "NOUN", "ADP", "PRON", "NOUN", "PUNCT",
    "CCONJ", "VERB", "PUNCT", "VERB", "ADV", "PUNCT", "PROPN", "PUNCT", "PRON", "AUX", "PART",
    "VERB", "PRON", "PUNCT", "CCONJ", "SCONJ", "PRON", "VERB", "DET", "NOUN", "PUNCT", "ADP",
    "DET", "PROPN", "PRON", "AUX", "VERB", "DET", "NOUN", "ADP", "PRON", "NOUN", "ADP", "PRON",
    "NOUN", "PUNCT", "VERB", "PRON", "ADP", "DET", "NOUN", "PUNCT", "CCONJ", "VERB", "PRON", "ADJ",
    "DET", "NOUN", "CCONJ", "NOUN", "PUNCT", "SCONJ", "PRON", "NOUN", "AUX", "VERB", "ADJ", "ADP",
    "ADP", "DET", "NOUN", "PUNCT", "AUX", "PRON", "VERB", "PUNCT", "CCONJ", "ADV", "PUNCT", "PRON",
    "ADV", "VERB", "ADV", "PRON", "VERB", "PRON", "ADJ", "ADP", "DET", "ADJ", "NOUN", "PUNCT",
    "PRON", "AUX", "VERB", "ADP", "ADP", "DET", "ADJ", "NOUN", "ADP", "VERB", "PRON", "NOUN",
    "ADP", "PRON", "NOUN", "PUNCT", //
    "DET", "NOUN", "ADP", "DET", "NOUN", "VERB", "ADP", "NOUN", "ADP", "DET", "PUNCT", "PROPN",
    "PROPN", "PUNCT", "AUX", "PART", "VERB", "DET", "NOUN", "SCONJ", "DET", "PROPN", "ADP",
    "PROPN", "AUX", "PUNCT", "ADP", "ADP", "PRON", "AUX", "NOUN", "CCONJ", "NOUN", "ADV", "PUNCT",
    "CCONJ", "ADP", "ADP", "DET", "ADJ", "ADJ", "NOUN", "PUNCT", "VERB", "ADP", "DET", "ADJ",
    "NOUN", "ADP", "NOUN", "ADV", "VERB", "ADP", "DET", "NOUN", "PUNCT", "ADV", "DET", "ADJ",
    "NOUN", "AUX", "ADV", "VERB", "PUNCT", //
    "ADV", "AUX", "PRON", "AUX", "VERB", "ADV", "DET", "ADJ", "NOUN", "AUX", "ADV", "ADV", "VERB",
    "ADP", "DET", "NOUN", "PUNCT", "ADV", "PRON", "AUX", "VERB", "ADP", "DET", "ADJ", "NOUN",
    "PUNCT", "CCONJ", "VERB", "ADP", "DET", "NOUN", "ADP", "DET", "NOUN", "PUNCT", "ADV", "PRON",
    "AUX", "ADV", "VERB", "ADV", "CCONJ", "VERB", "PUNCT", "CCONJ", "ADV", "PUNCT", "ADP", "DET",
    "NOUN", "PRON", "VERB", "DET", "NOUN", "ADP", "ADJ", "ADP", "DET", "NOUN", "ADP", "PRON",
    "DET", "NOUN", "AUX", "VERB", "PUNCT", "PRON", "ADJ", "ADJ", "NOUN", "VERB", "DET", "NOUN",
    "ADP", "PRON", "NOUN", "PUNCT", "ADV", "PUNCT", "ADP", "ADJ", "NOUN", "PUNCT", "PRON", "AUX",
    "VERB", "ADP", "DET", "NOUN", "PUNCT", "CCONJ", "PUNCT", "ADP", "PROPN", "PUNCT", "PROPN",
    "PUNCT", "CCONJ", "PROPN", "PUNCT", "PRON", "NOUN", "PUNCT", "NOUN", "PUNCT", "CCONJ", "NOUN",
    "VERB", "ADJ", "ADP", "DET", "NOUN", "PUNCT", "PUNCT", "CCONJ", "ADV", "PRON", "VERB", "PART",
    "VERB", "DET", "ADJ", "NOUN", "ADP", "DET", "NOUN", "ADP", "DET", "NOUN", "ADP", "VERB",
    "PUNCT", "VERB", "PUNCT", "SCONJ", "PRON", "AUX", "PUNCT", "DET", "ADJ", "NOUN", "ADP", "VERB",
    "ADP", "PRON", "NOUN", "ADP", "DET", "NOUN", "CCONJ", "VERB", "PRON", "ADP", "ADP", "DET",
    "NOUN", "PUNCT", "ADV", "ADV", "ADV", "NOUN", "VERB", "ADP", "PRON", "ADJ", "NOUN", "PUNCT",
    "VERB", "ADV", "ADP", "DET", "NOUN", "SCONJ", "ADV", "PUNCT", "CCONJ", "PUNCT", "INTJ",
    "PUNCT", //
    "DET", "ADJ", "NOUN", "AUX", "VERB", "PRON", "SCONJ", "PRON", "AUX", "PART", "VERB", "NOUN",
    "ADV", "PUNCT", "PRON", "AUX", "PART", "VERB", "ADV", "PUNCT", "SCONJ", "PRON", "VERB",
    "PROPN", "NOUN", "PUNCT", "SCONJ", "PRON", "AUX", "PART", "VERB", "ADP", "NOUN", "ADP", "DET",
    "NOUN", "PART", "VERB", "DET", "NOUN", "ADP", "DET", "NOUN", "NOUN", "PUNCT", "SCONJ", "NOUN",
    "ADP", "NOUN", "ADP", "PROPN", "AUX", "VERB", "ADV", "ADP", "NOUN", "ADP", "DET", "ADJ",
    "NOUN", "ADP", "PROPN", "PUNCT", "SCONJ", "NOUN", "ADV", "VERB", "NOUN", "ADP", "PRON", "NOUN",
    "PUNCT", "PART", "VERB", "ADP", "DET", "NOUN", "ADP", "NOUN", "NOUN", "PUNCT", "SCONJ", "NUM",
    "NOUN", "ADP", "NOUN", "VERB", "DET", "NOUN", "PUNCT", "NUM", "NOUN", "ADP", "DET", "NOUN",
    "PART", "NOUN", "DET", "NOUN", "PUNCT", "SCONJ", "PRON", "VERB", "NOUN", "NOUN", "PUNCT",
    "PRON", "ADP", "NOUN", "NOUN", "PUNCT", "SCONJ", "PRON", "AUX", "ADV", "VERB", "ADP", "PUNCT",
    "VERB", "PUNCT", "ADV", "PUNCT", "DET", "NOUN", "VERB", "VERB", "PUNCT", "CCONJ", "VERB",
    "DET", "ADJ", "NOUN", "ADP", "ADP", "DET", "NOUN", "PUNCT", "SCONJ", "ADP", "PRON", "ADJ",
    "NOUN", "CCONJ", "NOUN", "ADJ", "NOUN", "AUX", "ADV", "AUX", "VERB", "VERB", "PUNCT", "SCONJ",
    "ADP", "DET", "NOUN", "ADP", "NOUN", "NOUN", "PUNCT", //
    "CCONJ", "ADV", "SCONJ", "ADP", "DET", "ADJ", "NOUN", "CCONJ", "NOUN", "PUNCT", "ADP", "ADV",
    "ADJ", "CCONJ", "ADJ", "DET", "ADJ", "NOUN", "PUNCT", "PROPN", "PUNCT", "PUNCT", "DET", "ADJ",
    "NOUN", "NOUN", "VERB", "PUNCT", "VERB", "PART", "AUX", "VERB", "PRON", "NOUN", "ADP", "DET",
    "NOUN", "PUNCT", "PART", "VERB", "PRON", "DET", "ADV", "ADV", "ADV", "PUNCT", "ADV", "PUNCT",
    "SCONJ", "PRON", "VERB", "PRON", "ADV", "ADP", "DET", "ADJ", "NOUN", "CCONJ", "NOUN", "ADV",
    "PRON", "ADJ", "NOUN", "AUX", "AUX", "VERB", "PUNCT", "ADV", "SCONJ", "DET", "NOUN", "AUX",
    "AUX", "VERB", "PRON", "ADP", "DET", "ADJ", "NOUN", "ADJ", "AUX", "ADV", "VERB", "PROPN",
    "PROPN", "PUNCT", "PUNCT", "CCONJ", "ADV", "SCONJ", "DET", "PRON", "ADJ", "NOUN", "ADP", "ADJ",
    "NOUN", "ADV", "VERB", "PART", "VERB", "DET", "ADJ", "NOUN", "ADP", "PRON", "DET", "ADJ",
    "NOUN", "VERB", "PRON", "NOUN", "PUNCT", "SCONJ", "VERB", "CCONJ", "VERB", "ADP", "PUNCT",
    "ADV", "PRON", "AUX", "SCONJ", "PRON", "VERB", "DET", "PRON", "ADP", "DET", "ADJ", "NOUN",
    "PART", "NOUN", "PUNCT", "PRON", "PRON", "AUX", "ADV", "ADJ", "ADP", "ADJ", "NOUN", "PART",
    "VERB", "PUNCT", //
    "CCONJ", "PUNCT", "ADP", "DET", "NOUN", "PUNCT", "ADP", "NOUN", "CCONJ", "NOUN", "AUX", "DET",
    "NOUN", "ADV", "VERB", "ADP", "DET", "NOUN", "PUNCT", "SCONJ", "PROPN", "AUX", "ADP", "PRON",
    "PUNCT", "ADV", "VERB", "ADP", "PRON", "NOUN", "PUNCT", "CCONJ", "ADV", "VERB", "DET", "NOUN",
    "ADP", "NUM", "ADJ", "NOUN", "PUNCT", "PUNCT", "DET", "NOUN", "CCONJ", "DET", "NOUN", "PUNCT",
    "PUNCT", "CCONJ", "ADV", "PRON", "VERB", "PRON", "VERB", "ADP", "DET", "NOUN", "PUNCT",
    "PUNCT", "PRON", "ADJ", "NOUN", "VERB", "ADP", "DET", "NOUN", "PUNCT", "SCONJ", "SCONJ",
    "PART", "VERB", "PUNCT", "PRON", "NOUN", "VERB", "ADV", "ADP", "PRON", "NOUN", "PUNCT",
    "SCONJ", "SCONJ", "ADV", "ADJ", "PRON", "VERB", "PUNCT", "ADV", "DET", "NOUN", "CCONJ", "NOUN",
    "AUX", "VERB", "ADP", "PUNCT", "SCONJ", "PRON", "AUX", "PART", "VERB", "ADP", "PRON", "NOUN",
    "PUNCT", "CCONJ", "ADJ", "ADP", "DET", "ADJ", "NOUN", "PUNCT", "PRON", "AUX", "ADV", "VERB",
    "ADV", "SCONJ", "PUNCT", "ADP", "DET", "DET", "PUNCT", "PRON", "NOUN", "AUX", "ADV", "VERB",
    "ADP", "NOUN", "PUNCT", "CCONJ", "SCONJ", "PRON", "AUX", "ADV", "ADV", "VERB", "PUNCT", "DET",
    "NOUN", "PUNCT", "SCONJ", "PRON", "VERB", "ADV", "ADP", "DET", "NOUN", "ADP", "DET", "ADJ",
    "NOUN", "ADP", "DET", "NOUN", "PUNCT", "CCONJ", "DET", "ADJ", "NOUN", "VERB", "ADP", "NOUN",
    "ADP", "NOUN", "ADP", "DET", "ADJ", "NOUN", "CCONJ", "NOUN", "PUNCT", //
    "ADP", "ADJ", "PART", "VERB", "PUNCT", "ADV", "PUNCT", "ADV", "ADJ", "PART", "VERB", "PUNCT",
    "ADP", "NOUN", "PUNCT", "DET", "NOUN", "ADJ", "ADP", "ADV", "ADJ", "CCONJ", "ADJ", "DET",
    "NOUN", "PUNCT", "ADP", "DET", "ADJ", "NOUN", "PUNCT", "DET", "NOUN", "ADP", "PRON", "DET",
    "NOUN", "ADP", "PRON", "ADJ", "ADJ", "NOUN", "AUX", "VERB", "PUNCT", "DET", "NOUN", "PUNCT",
    "ADP", "PRON", "DET", "ADJ", "NOUN", "VERB", "ADP", "NOUN", "PUNCT", "DET", "NOUN", "ADV",
    "ADV", "ADJ", "SCONJ", "PRON", "PUNCT", "ADV", "ADV", "VERB", "PART", "VERB", "DET", "DET",
    "NOUN", "ADP", "DET", "ADJ", "NOUN", "PUNCT", "ADJ", "PART", "VERB", "NOUN", "ADP", "DET",
    "NOUN", "ADV", "DET", "NOUN", "ADJ", "ADP", "DET", "NOUN", "ADP", "PRON", "PUNCT", "PUNCT",
    "ADJ", "ADJ", "PROPN", "VERB", "ADV", "PUNCT", "VERB", "DET", "NOUN", "ADP", "ADJ", "NOUN",
    "PUNCT", "VERB", "ADP", "ADP", "DET", "NOUN", "PART", "VERB", "DET", "NOUN", "NOUN", "ADV",
    "PUNCT", "ADV", "VERB", "ADP", "NOUN", "PUNCT", "CCONJ", "VERB", "ADP", "NOUN", "PUNCT",
    "VERB", "ADP", "DET", "ADJ", "CCONJ", "ADJ", "NOUN", "PUNCT", "ADV", "VERB", "ADP", "DET",
    "ADJ", "ADJ", "ADJ", "NOUN", "PUNCT", "VERB", "ADP", "DET", "NOUN", "PUNCT", "VERB", "ADV",
    "PUNCT", "VERB", "ADV", "CCONJ", "ADV", "PUNCT", "VERB", "ADV", "CCONJ", "ADV", "PUNCT",
    "CCONJ", "ADP", "ADJ", "PUNCT", "ADV", "VERB", "DET", "NOUN", "ADP", "PRON", "NOUN", "PUNCT",
    "ADV", "VERB", "ADJ", "PROPN", "ADP", "DET", "NOUN", "PUNCT", "CCONJ", "VERB", "ADP", "DET",
    "NOUN", "PUNCT", "ADP", "DET", "NOUN", "VERB", "VERB", "ADV", "ADP", "PRON", "NOUN", "PUNCT",
    "ADV", "ADV", "SCONJ", "PART", "VERB", "PUNCT", "PUNCT", "ADV", "PUNCT", "NOUN", "PROPN",
    "PUNCT", "PRON", "AUX", "VERB", "PRON", "PUNCT", "INTJ", "PUNCT", "PRON", "AUX", "PUNCT",
    "PUNCT", //
];

#[test]
fn hard_eval_meets_bar() {
    assert_eq!(TOKENS4.len(), GOLD4.len());
    let model = Model::from_json(include_str!("../weights/upos.json")).unwrap();
    let got = model.tag(TOKENS4);
    assert_eq!(got.len(), GOLD4.len());
    let wrong: Vec<(usize, &str, &str, &str)> = got
        .iter()
        .zip(GOLD4.iter())
        .zip(TOKENS4.iter())
        .enumerate()
        .filter(|(_, ((t, g), _))| t.upos() != **g)
        .map(|(i, ((t, g), w))| (i, *w, t.upos(), *g))
        .collect();
    let accuracy = 1.0 - wrong.len() as f64 / GOLD4.len() as f64;
    eprintln!("hard misses (index, token, got, gold): {wrong:?}");
    eprintln!("hard accuracy: {accuracy:.4}");
    assert!(
        accuracy >= 0.84,
        "hard eval accuracy {accuracy:.3} below bar; move deliberately with model changes",
    );
}
