//! Shipped lexical backoff lists for gated correction rules.
//!
//! One wordlist (committed, provenance in the file header):
//! `verbs.txt`: EWT VERB lemmas — generated, see
//! `scripts/verb-lemmas.sh`. A NOUN-predicted `-s` word flips to
//! VERB only when its stem is a known base form; that membership
//! test is what separates `glitters`/`wears` from `theories` and
//! `status`, which killed the morphology-only rule.
//!
//! Lookup is binary search over sorted lines; the list is consulted
//! only below the margin gate, so steady-state cost is ~nil. This is
//! a backoff, never a tagdict: nothing here is consulted on the fast
//! path or bypasses the perceptron — the gate in `correction.rs`
//! decides every firing.

use std::sync::LazyLock;

use crate::Tag;

fn load_list(text: &'static str) -> Vec<&'static str> {
    // Comment rule: `# ` (hash+space) + empties only. Bare `#`-led
    // tokens (`#`, `###`, `#'s`, `#e` — real GloVe/EWT words) must
    // survive: dropping them misaligns row-indexed tables and flips
    // the OOV gate the wrong way. All file headers use `# `.
    let mut v: Vec<&'static str> = text
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with("# "))
        .collect();
    v.sort_unstable();
    v
}

static VERB_LEMMAS: LazyLock<Vec<&'static str>> =
    LazyLock::new(|| load_list(include_str!("../lexicon/verbs.txt")));

fn contains(list: &[&str], word: &str) -> bool {
    list.binary_search(&word).is_ok()
}

/// True when pre-lowered `w` is a known verb base form or a regular
/// `-s` inflection of one (`wears`→`wear`, `watches`→`watch`,
/// `tries`/`flies`→`try`/`fly`). Callers pass already-lowercased
/// text (the correction layer holds a pre-lowered slice) so this
/// never allocates, except the `ies`→`y` restem which fires solely
/// on `-ies` words. Never strips `ss` (`glass`, `status`); bare
/// `-s` words whose stem is not a verb (`theories`→`theory`,
/// `news`→`new`, `arms`→`arm` is — see below) correctly abstain.
///
/// NOTE on `arms`/`means`/`thanks`: their stems (`arm`, `mean`,
/// `thank`) ARE verb lemmas, so this returns true and the calling
/// rule's context conditions (nominal prev, complement next) plus
/// the margin gate must carry the precision — `folded his arms`
/// (prev PRON, next end) is the known-risk shape. Measured, not
/// assumed: see `--correct` reporting.
pub fn known_verb_form(w: &str) -> bool {
    if contains(&VERB_LEMMAS, w) {
        return true;
    }
    let b = w.as_bytes();
    if b.len() <= 3 || w.ends_with("ss") {
        return false;
    }
    if let Some(stripped) = w.strip_suffix("ies") {
        let mut cand = stripped.to_string();
        cand.push('y');
        if contains(&VERB_LEMMAS, cand.as_str()) {
            return true;
        }
    }
    if let Some(stripped) = w.strip_suffix("es")
        && contains(&VERB_LEMMAS, stripped)
    {
        return true;
    }
    if let Some(stripped) = w.strip_suffix('s') {
        return contains(&VERB_LEMMAS, stripped);
    }
    false
}

// --- NN backoff (R3-3) ---
//
// `nn-words.txt` (60k universe, file order = row order) +
// `nn-vec.bin` (row-major f16-LE, 50 dims) + `nn-targets.txt`
// (rowidx + EWT-train majority tag) + `train-vocab.txt` (OOV gate).
// Generated by `scripts/nn-vectors.py` (vectors: GloVe-50, Public
// Domain Dedication, https://nlp.stanford.edu/projects/glove/).
// Consulted only below the margin gate for train-vocab-OOV words:
// nearest target row by cosine → its majority tag. Steady-state
// cost ~nil (gated, rare); the 6 MB blob parses once on first gated
// fire via LazyLock, never on the fast path.

static TRAIN_VOCAB: LazyLock<Vec<&'static str>> =
    LazyLock::new(|| load_list(include_str!("../lexicon/train-vocab.txt")));

/// True when pre-lowered `w` never appeared in EWT train.
pub fn is_oov(w: &str) -> bool {
    !contains(&TRAIN_VOCAB, w)
}

struct NnTable {
    /// Row index per word for O(1) query lookup.
    index: std::collections::HashMap<&'static str, u32>,
    /// f32 vectors, row-major (converted once from f16-LE).
    vecs: Vec<f32>,
    /// Target rows: (rowidx, majority tag), sorted by rowidx.
    targets: Vec<(u32, Tag)>,
    /// Precomputed target norms (cosine denominator halves).
    norms: Vec<f32>,
}

/// Manual f16-LE → f32 (`f16` is still unstable on this toolchain):
/// sign + 5-bit exponent (bias 15) + 10-bit mantissa, with
/// subnormal/Inf/NaN handling.
fn f16_to_f32(bits: u16) -> f32 {
    let sign = ((bits >> 15) & 1) as u32;
    let exp = ((bits >> 10) & 0x1f) as u32;
    let mant = (bits & 0x3ff) as u32;
    let f = if exp == 0 {
        // Subnormal (incl. zero): renormalize.
        if mant == 0 {
            sign << 31
        } else {
            let mut m = mant;
            let mut e = 127 - 15;
            while m & 0x400 == 0 {
                m <<= 1;
                e -= 1;
            }
            m &= 0x3ff;
            (sign << 31) | (e << 23) | (m << 13)
        }
    } else if exp == 0x1f {
        (sign << 31) | (0xff << 23) | (mant << 13)
    } else {
        (sign << 31) | ((exp + 112) << 23) | (mant << 13)
    };
    f32::from_bits(f)
}

fn parse_nn() -> NnTable {
    // File order is row order — do NOT sort. Comment rule matches
    // `load_list` (`# ` only — bare `#` tokens are real words).
    let words: Vec<&'static str> = include_str!("../lexicon/nn-words.txt")
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with("# "))
        .collect();
    let n_rows = words.len();
    let index: std::collections::HashMap<&'static str, u32> = words
        .iter()
        .enumerate()
        .map(|(i, w)| (*w, i as u32))
        .collect();
    drop(words);
    let raw: &[u8] = include_bytes!("../lexicon/nn-vec.bin");
    assert_eq!(raw.len(), n_rows * 50 * 2, "nn-vec shape");
    let vecs: Vec<f32> = raw
        .chunks_exact(2)
        .map(|b| f16_to_f32(u16::from_le_bytes([b[0], b[1]])))
        .collect();
    let mut targets: Vec<(u32, Tag)> = Vec::new();
    for line in include_str!("../lexicon/nn-targets.txt").lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with("# ") {
            continue;
        }
        let mut parts = line.split_whitespace();
        if let (Some(idx), Some(tag), None) = (parts.next(), parts.next(), parts.next())
            && let Ok(i) = idx.parse::<u32>()
            && let Some(t) = Tag::from_upos(tag)
        {
            targets.push((i, t));
        }
    }
    targets.sort_unstable_by_key(|(i, _)| *i);
    let mut norms = vec![0.0f32; targets.len()];
    for (k, (row, _)) in targets.iter().enumerate() {
        let base = *row as usize * 50;
        let mut s = 0.0f32;
        for v in &vecs[base..base + 50] {
            s += v * v;
        }
        norms[k] = s.sqrt().max(1e-9);
    }
    NnTable {
        index,
        vecs,
        targets,
        norms,
    }
}

static NN: LazyLock<NnTable> = LazyLock::new(parse_nn);

fn cosine_row(table: &NnTable, query: &[f32; 50], qnorm: f32, k: usize) -> f32 {
    let base = table.targets[k].0 as usize * 50;
    let row = &table.vecs[base..base + 50];
    let mut s = 0.0f32;
    for (a, b) in row.iter().zip(query.iter()) {
        s += a * b;
    }
    s / (table.norms[k] * qnorm)
}

/// Majority tag of the nearest target row for pre-lowered OOV `w`;
/// `None` when uncovered. Consulted only below the margin gate.
pub fn nn_tag(w: &str) -> Option<Tag> {
    let table = &*NN;
    let row = *table.index.get(w)?;
    let base = row as usize * 50;
    let mut query = [0.0f32; 50];
    query.copy_from_slice(&table.vecs[base..base + 50]);
    let mut qn = 0.0f32;
    for v in &query {
        qn += v * v;
    }
    let qnorm = qn.sqrt().max(1e-9);
    let mut best = 0usize;
    let mut best_s = f32::NEG_INFINITY;
    for k in 0..table.targets.len() {
        let s = cosine_row(table, &query, qnorm, k);
        if s > best_s {
            best_s = s;
            best = k;
        }
    }
    Some(table.targets[best].1)
}
