#!/usr/bin/env python3
"""Build the NN-backoff tables for the `oov-nn` correction rule.

Offline infrastructure (kept, like scripts/verb-lemmas.sh): reads EWT
train (tag majorities + vocab) and GloVe-50 (Public Domain Dedication;
vectors at https://nlp.stanford.edu/projects/glove/, fetched once to
/tmp, never vendored), writes three committed files under
crates/english-pos/lexicon/ with provenance headers:
  nn-words.txt   : 61.6k query/target universe words (glove top-60k
                   frequency order + in-vocab train targets), 1/line
  nn-vec.bin     : row-major float16-LE vectors, same order (no header)
  nn-targets.txt : rowidx + majority tag for the 13.4k train-vocab
                   target rows (`<idx> <TAG>`)
Plus train-vocab.txt (16.6k lowercased EWT-train forms for the OOV
gate). Shaping measurements: R3-3 sizing probes (f16 holds f32 nets
dev +14 / test +11 at tau=2.0; int8 targets go net-negative on test).
"""
import struct
import sys
from collections import Counter

import numpy as np

UD = "/tmp/ud/ewt/en_ewt-ud-train.conllu"
GLOVE = "/tmp/opencode/round3/glove.6B.50d.txt"
OUT = "crates/english-pos/lexicon"


def read(path):
    for line in open(path):
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        c = s.split("\t")
        if len(c) < 5 or "-" in c[0] or "." in c[0]:
            continue
        yield c[1], c[3]


def main():
    import sys
    paths = [UD] + [a for a in sys.argv[1:] if not a.startswith("-")]
    maj = {}
    for path in paths:
        for w, t in read(path):
            maj.setdefault(w.lower(), Counter())[t] += 1
    majtag = {w: c.most_common(1)[0][0] for w, c in maj.items()}
    vocab = set(maj)
    gw = []
    with open(GLOVE, encoding="utf-8") as f:
        for line in f:
            w = line.split(" ", 1)[0]
            gw.append(w)
            if len(gw) >= 60000:
                break
    print(f"train vocab {len(vocab)}, glove top-60k {len(gw)}", flush=True)
    targets = [w for w in vocab if w in set(gw)]
    print(f"targets in universe: {len(targets)}/{len(vocab)}", flush=True)
    uni = list(dict.fromkeys(gw + targets))  # universe first, then stragglers
    gi = {w: i for i, w in enumerate(gw)}
    # stream vectors for universe rows only
    vecs = {}
    with open(GLOVE, encoding="utf-8") as f:
        for line in f:
            w, _, _ = line.split(" ", 2)[0], None, None
            if w in set(uni) and w not in vecs:
                p = line.rstrip("\n").split(" ")
                if len(p) == 51:
                    vecs[w] = np.array([float(x) for x in p[1:]], dtype=np.float32)
            if len(vecs) >= len(uni):
                break
    assert len(vecs) == len(uni), (len(vecs), len(uni))
    with open(f"{OUT}/nn-words.txt", "w") as f:
        f.write("# NN-backoff universe: glove top-60k frequency order + "
                "in-vocab train targets. Generated by scripts/nn-vectors.py "
                "(vectors: GloVe-50, Public Domain Dedication, "
                "https://nlp.stanford.edu/projects/glove/).\n")
        f.write("\n".join(uni) + "\n")
    with open(f"{OUT}/nn-vec.bin", "wb") as f:
        for w in uni:
            f.write(struct.pack("<50e", *vecs[w].tolist()))
    idx = {w: i for i, w in enumerate(uni)}
    with open(f"{OUT}/nn-targets.txt", "w") as f:
        f.write("# rowidx + EWT-train majority tag for target rows. Same provenance.\n")
        for w in targets:
            f.write(f"{idx[w]} {majtag[w]}\n")
    with open(f"{OUT}/train-vocab.txt", "w") as f:
        f.write("# Lowercased EWT-train forms (OOV gate). Generated, same script.\n")
        f.write("\n".join(sorted(vocab)) + "\n")
    import hashlib
    for p in ("nn-words.txt", "nn-vec.bin", "nn-targets.txt", "train-vocab.txt"):
        b = open(f"{OUT}/{p}", "rb").read()
        print(f"{p}: {len(b)} bytes md5 {hashlib.md5(b).hexdigest()}")


main()
