//! Hard-prose chunk eval: hand-verified gold over the 10
//! `hard.rs` tagger-eval sentences (tokens/tags repeated here so
//! this crate stays self-contained).
//!
//! Two tests over one canonical table (mirrors `genre.rs`):
//! - `hard_rule_chunks`: gold tags -> gold chunks, exact (bar 1.0
//!   pin: implementation == spec in `README.md`).
//! - `hard_end_to_end`: model tags -> chunks vs gold. Sentence-exact
//!   rate + token-kind accuracy printed; bar below measured.
//!
//! Gold chunks were proposed by an independent spec port and
//! verified boundary-by-boundary against `README.md` (MWE hits,
//! PRON-continuations, lone-DET strandings, Prep absorption all
//! checked); the Rust suite re-checks every one.

use english_chunk::{ChunkKind, ChunkKind as K, chunk_tagged};
use english_pos::{Model, Tag};

/// Canonical table: (tokens, gold tags, gold chunks) per sentence.
#[rustfmt::skip]
const SENTENCES: &[(&[&str], &[Tag], &[ChunkKind])] = &[
    (
        &["And", "when", "we", "consider", "that", "other", "theory", "of", "the", "natural", "philosophers", ",", "that", "all", "other", "earthly", "hues", "—", "every", "stately", "or", "lovely", "emblazoning", "—", "the", "sweet", "tinges", "of", "sunset", "skies", "and", "woods", ";", "yea", "and", "the", "gilded", "velvets", "of", "butterflies", "and", "the", "butterfly", "cheeks", "of", "young", "girls", ";", "all", "these", "are", "but", "subtile", "deceits", ",", "not", "actually", "inherent", "in", "substances", ",", "but", "only", "laid", "on", "from", "without", ";", "so", "that", "all", "deified", "Nature", "absolutely", "paints", "like", "the", "harlot", ",", "whose", "allurements", "cover", "nothing", "but", "the", "charnel-house", "within", ";", "and", "when", "we", "proceed", "further", "and", "consider", "that", "the", "mystical", "cosmetic", "which", "produces", "every", "one", "of", "her", "hues", ",", "the", "great", "principle", "of", "light", ",", "for", "ever", "remains", "white", "or", "colorless", "in", "itself", ",", "and", "if", "operating", "without", "medium", "upon", "matter", ",", "would", "touch", "all", "objects", ",", "even", "tulips", "and", "roses", ",", "with", "its", "own", "blank", "tinge", "—", "pondering", "all", "this", ",", "the", "palsied", "universe", "lies", "before", "us", "a", "leper", ";", "and", "like", "wilful", "travellers", "in", "Lapland", ",", "who", "refuse", "to", "wear", "coloured", "and", "colouring", "glasses", "upon", "their", "eyes", ",", "so", "the", "wretched", "infidel", "gazes", "himself", "blind", "at", "the", "monumental", "white", "shroud", "that", "wraps", "all", "the", "prospect", "around", "him", "."],
        &[Tag::Cconj, Tag::Adv, Tag::Pron, Tag::Verb, Tag::Sconj, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Det, Tag::Adj, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Det, Tag::Adj, Tag::Cconj, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Noun, Tag::Cconj, Tag::Noun, Tag::Punct, Tag::Intj, Tag::Cconj, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Cconj, Tag::Det, Tag::Noun, Tag::Noun, Tag::Adp, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Det, Tag::Det, Tag::Aux, Tag::Cconj, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Part, Tag::Adv, Tag::Adj, Tag::Adp, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Adv, Tag::Verb, Tag::Adp, Tag::Adp, Tag::Adv, Tag::Punct, Tag::Sconj, Tag::Sconj, Tag::Det, Tag::Adj, Tag::Propn, Tag::Adv, Tag::Verb, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Pron, Tag::Noun, Tag::Verb, Tag::Pron, Tag::Cconj, Tag::Det, Tag::Noun, Tag::Adv, Tag::Punct, Tag::Cconj, Tag::Adv, Tag::Pron, Tag::Verb, Tag::Adv, Tag::Cconj, Tag::Verb, Tag::Sconj, Tag::Det, Tag::Adj, Tag::Noun, Tag::Pron, Tag::Verb, Tag::Det, Tag::Pron, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Punct, Tag::Adp, Tag::Adv, Tag::Verb, Tag::Adj, Tag::Cconj, Tag::Adj, Tag::Adp, Tag::Pron, Tag::Punct, Tag::Cconj, Tag::Sconj, Tag::Verb, Tag::Adp, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Punct, Tag::Aux, Tag::Verb, Tag::Det, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Noun, Tag::Cconj, Tag::Noun, Tag::Punct, Tag::Adp, Tag::Pron, Tag::Adj, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Verb, Tag::Det, Tag::Pron, Tag::Punct, Tag::Det, Tag::Adj, Tag::Noun, Tag::Verb, Tag::Adp, Tag::Pron, Tag::Det, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Adp, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Propn, Tag::Punct, Tag::Pron, Tag::Verb, Tag::Part, Tag::Verb, Tag::Adj, Tag::Cconj, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Det, Tag::Adj, Tag::Noun, Tag::Verb, Tag::Pron, Tag::Adj, Tag::Adp, Tag::Det, Tag::Adj, Tag::Adj, Tag::Noun, Tag::Pron, Tag::Verb, Tag::Det, Tag::Det, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Punct],
        &[K::Conj, K::Adverb, K::Noun, K::Verb, K::Subord, K::Noun, K::Prep, K::Punct, K::Subord, K::Noun, K::Punct, K::Noun, K::Adj, K::Conj, K::Noun, K::Punct, K::Noun, K::Prep, K::Conj, K::Noun, K::Punct, K::Interj, K::Conj, K::Noun, K::Prep, K::Conj, K::Noun, K::Prep, K::Punct, K::Noun, K::Noun, K::Verb, K::Conj, K::Noun, K::Punct, K::Particle, K::Adverb, K::Adj, K::Prep, K::Punct, K::Conj, K::Adverb, K::Verb, K::Prep, K::Prep, K::Adverb, K::Punct, K::Subord, K::Noun, K::Adverb, K::Verb, K::Prep, K::Punct, K::Noun, K::Verb, K::Noun, K::Conj, K::Noun, K::Adverb, K::Punct, K::Conj, K::Adverb, K::Noun, K::Verb, K::Adverb, K::Conj, K::Verb, K::Subord, K::Noun, K::Noun, K::Verb, K::Noun, K::Prep, K::Punct, K::Noun, K::Prep, K::Punct, K::Prep, K::Adverb, K::Verb, K::Adj, K::Conj, K::Adj, K::Prep, K::Punct, K::Conj, K::Subord, K::Verb, K::Prep, K::Prep, K::Punct, K::Verb, K::Noun, K::Punct, K::Adverb, K::Noun, K::Conj, K::Noun, K::Punct, K::Prep, K::Punct, K::Verb, K::Noun, K::Punct, K::Noun, K::Verb, K::Prep, K::Punct, K::Conj, K::Prep, K::Prep, K::Punct, K::Noun, K::Verb, K::Particle, K::Verb, K::Adj, K::Conj, K::Noun, K::Prep, K::Punct, K::Adverb, K::Noun, K::Verb, K::Noun, K::Adj, K::Prep, K::Verb, K::Noun, K::Prep, K::Punct],
    ),
    (
        &["If", "two", "strangers", "crossing", "the", "Pine", "Barrens", "in", "New", "York", "State", "or", "the", "equally", "desolate", "Salisbury", "Plain", "in", "England", ";", "if", "casually", "encountering", "each", "other", "in", "such", "inhospitable", "wilds", ",", "these", "twain", ",", "for", "the", "life", "of", "them", ",", "can", "not", "well", "avoid", "a", "mutual", "salutation", ";", "and", "stopping", "for", "a", "moment", "to", "interchange", "the", "news", ";", "and", ",", "perhaps", ",", "sitting", "down", "for", "a", "while", "and", "resting", "in", "concert", ":", "then", ",", "how", "much", "more", "natural", "that", "upon", "the", "illimitable", "Pine", "Barrens", "and", "Salisbury", "Plains", "of", "the", "sea", ",", "two", "whaling", "vessels", "descrying", "each", "other", "at", "the", "ends", "of", "the", "earth", "—", "off", "lone", "Fanning", "'s", "Island", ",", "or", "the", "far", "away", "King", "'s", "Mills", ";", "how", "much", "more", "natural", ",", "I", "say", ",", "that", "under", "such", "circumstances", "these", "ships", "should", "not", "only", "interchange", "hails", ",", "but", "come", "into", "still", "closer", ",", "more", "friendly", "and", "sociable", "contact", "."],
        &[Tag::Sconj, Tag::Num, Tag::Noun, Tag::Verb, Tag::Det, Tag::Propn, Tag::Propn, Tag::Adp, Tag::Propn, Tag::Propn, Tag::Propn, Tag::Cconj, Tag::Det, Tag::Adv, Tag::Adj, Tag::Propn, Tag::Propn, Tag::Adp, Tag::Propn, Tag::Punct, Tag::Sconj, Tag::Adv, Tag::Verb, Tag::Det, Tag::Adj, Tag::Adp, Tag::Adj, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Det, Tag::Num, Tag::Punct, Tag::Adp, Tag::Det, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Punct, Tag::Aux, Tag::Part, Tag::Adv, Tag::Verb, Tag::Det, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Verb, Tag::Adp, Tag::Det, Tag::Noun, Tag::Part, Tag::Verb, Tag::Det, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Punct, Tag::Adv, Tag::Punct, Tag::Verb, Tag::Adp, Tag::Adp, Tag::Det, Tag::Noun, Tag::Cconj, Tag::Verb, Tag::Adp, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Punct, Tag::Adv, Tag::Adv, Tag::Adv, Tag::Adj, Tag::Sconj, Tag::Adp, Tag::Det, Tag::Adj, Tag::Propn, Tag::Propn, Tag::Cconj, Tag::Propn, Tag::Propn, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Num, Tag::Noun, Tag::Noun, Tag::Verb, Tag::Det, Tag::Adj, Tag::Adp, Tag::Det, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Adj, Tag::Propn, Tag::Part, Tag::Propn, Tag::Punct, Tag::Cconj, Tag::Det, Tag::Adv, Tag::Adv, Tag::Propn, Tag::Part, Tag::Propn, Tag::Punct, Tag::Adv, Tag::Adv, Tag::Adv, Tag::Adj, Tag::Punct, Tag::Pron, Tag::Verb, Tag::Punct, Tag::Sconj, Tag::Adp, Tag::Adj, Tag::Noun, Tag::Det, Tag::Noun, Tag::Aux, Tag::Part, Tag::Adv, Tag::Verb, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Verb, Tag::Adp, Tag::Adv, Tag::Adj, Tag::Punct, Tag::Adv, Tag::Adj, Tag::Cconj, Tag::Adj, Tag::Noun, Tag::Punct],
        &[K::Subord, K::Noun, K::Verb, K::Noun, K::Prep, K::Conj, K::Noun, K::Adverb, K::Noun, K::Prep, K::Punct, K::Subord, K::Adverb, K::Verb, K::Noun, K::Adj, K::Prep, K::Punct, K::Noun, K::Noun, K::Punct, K::Prep, K::Prep, K::Punct, K::Verb, K::Particle, K::Adverb, K::Verb, K::Noun, K::Punct, K::Conj, K::Verb, K::Prep, K::Particle, K::Verb, K::Noun, K::Punct, K::Conj, K::Punct, K::Adverb, K::Punct, K::Verb, K::Prep, K::Prep, K::Conj, K::Verb, K::Prep, K::Punct, K::Adverb, K::Punct, K::Adverb, K::Adj, K::Subord, K::Prep, K::Conj, K::Noun, K::Prep, K::Punct, K::Noun, K::Verb, K::Noun, K::Adj, K::Prep, K::Prep, K::Punct, K::Adverb, K::Noun, K::Particle, K::Noun, K::Punct, K::Conj, K::Noun, K::Adverb, K::Noun, K::Particle, K::Noun, K::Punct, K::Adverb, K::Adj, K::Punct, K::Noun, K::Verb, K::Punct, K::Subord, K::Prep, K::Verb, K::Particle, K::Adverb, K::Verb, K::Noun, K::Punct, K::Conj, K::Verb, K::Prep, K::Adverb, K::Adj, K::Punct, K::Adverb, K::Adj, K::Conj, K::Noun, K::Punct],
    ),
    (
        &["I", "well", "know", "that", "these", "Crappoes", "of", "Frenchmen", "are", "but", "poor", "devils", "in", "the", "fishery", ";", "sometimes", "lowering", "their", "boats", "for", "breakers", ",", "mistaking", "them", "for", "Sperm", "Whale", "spouts", ";", "yes", "and", "sometimes", "sailing", "from", "their", "port", "with", "their", "hold", "full", "of", "boxes", "of", "tallow", "candles", "and", "cases", "of", "snuffers", ",", "foreseeing", "that", "all", "the", "oil", "they", "will", "get", "wo", "n't", "be", "enough", "to", "dip", "the", "Captain", "'s", "wick", "into", ";", "aye", ",", "we", "all", "know", "these", "things", ";", "but", "look", "ye", ",", "here", "'s", "a", "Crappo", "that", "is", "content", "with", "our", "leavings", ",", "the", "drugged", "whale", "there", ",", "I", "mean", ";", "aye", ",", "and", "is", "content", "too", "with", "scraping", "the", "dry", "bones", "of", "that", "other", "precious", "fish", "he", "has", "there", "."],
        &[Tag::Pron, Tag::Adv, Tag::Verb, Tag::Sconj, Tag::Det, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Aux, Tag::Cconj, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Verb, Tag::Pron, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Punct, Tag::Verb, Tag::Pron, Tag::Adp, Tag::Noun, Tag::Noun, Tag::Noun, Tag::Punct, Tag::Intj, Tag::Cconj, Tag::Adv, Tag::Verb, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Adj, Tag::Adp, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Noun, Tag::Cconj, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Punct, Tag::Verb, Tag::Sconj, Tag::Det, Tag::Det, Tag::Noun, Tag::Pron, Tag::Aux, Tag::Verb, Tag::Aux, Tag::Part, Tag::Aux, Tag::Adj, Tag::Part, Tag::Verb, Tag::Det, Tag::Propn, Tag::Part, Tag::Noun, Tag::Adp, Tag::Punct, Tag::Intj, Tag::Punct, Tag::Pron, Tag::Det, Tag::Verb, Tag::Det, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Verb, Tag::Pron, Tag::Punct, Tag::Adv, Tag::Verb, Tag::Det, Tag::Noun, Tag::Pron, Tag::Aux, Tag::Adj, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adv, Tag::Punct, Tag::Pron, Tag::Verb, Tag::Punct, Tag::Intj, Tag::Punct, Tag::Cconj, Tag::Aux, Tag::Adj, Tag::Adv, Tag::Adp, Tag::Verb, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Det, Tag::Adj, Tag::Adj, Tag::Noun, Tag::Pron, Tag::Verb, Tag::Adv, Tag::Punct],
        &[K::Noun, K::Adverb, K::Verb, K::Subord, K::Noun, K::Prep, K::Verb, K::Conj, K::Noun, K::Prep, K::Punct, K::Adverb, K::Verb, K::Noun, K::Prep, K::Punct, K::Verb, K::Noun, K::Prep, K::Punct, K::Interj, K::Conj, K::Adverb, K::Verb, K::Prep, K::Prep, K::Prep, K::Prep, K::Conj, K::Noun, K::Prep, K::Punct, K::Verb, K::Subord, K::Noun, K::Noun, K::Verb, K::Verb, K::Particle, K::Verb, K::Adj, K::Particle, K::Verb, K::Noun, K::Particle, K::Noun, K::Prep, K::Punct, K::Interj, K::Punct, K::Noun, K::Noun, K::Verb, K::Noun, K::Punct, K::Conj, K::Verb, K::Noun, K::Punct, K::Adverb, K::Verb, K::Noun, K::Noun, K::Verb, K::Adj, K::Prep, K::Punct, K::Noun, K::Adverb, K::Punct, K::Noun, K::Verb, K::Punct, K::Interj, K::Punct, K::Conj, K::Verb, K::Adj, K::Adverb, K::Prep, K::Verb, K::Noun, K::Prep, K::Verb, K::Adverb, K::Punct],
    ),
    (
        &["But", "I", "am", "going", "now", "to", "keep", "a", "sharp", "look-out", "on", "him", ";", "and", "if", "I", "see", "anything", "very", "suspicious", "going", "on", ",", "I", "'ll", "just", "take", "him", "by", "the", "nape", "of", "his", "neck", ",", "and", "say", "—", "Look", "here", ",", "Beelzebub", ",", "you", "do", "n't", "do", "it", ";", "and", "if", "he", "makes", "any", "fuss", ",", "by", "the", "Lord", "I", "'ll", "make", "a", "grab", "into", "his", "pocket", "for", "his", "tail", ",", "take", "it", "to", "the", "capstan", ",", "and", "give", "him", "such", "a", "wrenching", "and", "heaving", ",", "that", "his", "tail", "will", "come", "short", "off", "at", "the", "stump", "—", "do", "you", "see", ";", "and", "then", ",", "I", "rather", "guess", "when", "he", "finds", "himself", "docked", "in", "that", "queer", "fashion", ",", "he", "'ll", "sneak", "off", "without", "the", "poor", "satisfaction", "of", "feeling", "his", "tail", "between", "his", "legs", "."],
        &[Tag::Cconj, Tag::Pron, Tag::Aux, Tag::Verb, Tag::Adv, Tag::Part, Tag::Verb, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Punct, Tag::Cconj, Tag::Sconj, Tag::Pron, Tag::Verb, Tag::Pron, Tag::Adv, Tag::Adj, Tag::Verb, Tag::Adp, Tag::Punct, Tag::Pron, Tag::Aux, Tag::Adv, Tag::Verb, Tag::Pron, Tag::Adp, Tag::Det, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Verb, Tag::Punct, Tag::Verb, Tag::Adv, Tag::Punct, Tag::Propn, Tag::Punct, Tag::Pron, Tag::Aux, Tag::Part, Tag::Verb, Tag::Pron, Tag::Punct, Tag::Cconj, Tag::Sconj, Tag::Pron, Tag::Verb, Tag::Det, Tag::Noun, Tag::Punct, Tag::Adp, Tag::Det, Tag::Propn, Tag::Pron, Tag::Aux, Tag::Verb, Tag::Det, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Verb, Tag::Pron, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Verb, Tag::Pron, Tag::Adj, Tag::Det, Tag::Noun, Tag::Cconj, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Pron, Tag::Noun, Tag::Aux, Tag::Verb, Tag::Adj, Tag::Adp, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Aux, Tag::Pron, Tag::Verb, Tag::Punct, Tag::Cconj, Tag::Adv, Tag::Punct, Tag::Pron, Tag::Adv, Tag::Verb, Tag::Adv, Tag::Pron, Tag::Verb, Tag::Pron, Tag::Adj, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Pron, Tag::Aux, Tag::Verb, Tag::Adp, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Verb, Tag::Pron, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct],
        &[K::Conj, K::Noun, K::Verb, K::Adverb, K::Particle, K::Verb, K::Noun, K::Prep, K::Punct, K::Conj, K::Subord, K::Noun, K::Verb, K::Noun, K::Adverb, K::Adj, K::Verb, K::Prep, K::Punct, K::Noun, K::Verb, K::Adverb, K::Verb, K::Noun, K::Prep, K::Prep, K::Punct, K::Conj, K::Verb, K::Punct, K::Verb, K::Adverb, K::Punct, K::Noun, K::Punct, K::Noun, K::Verb, K::Particle, K::Verb, K::Noun, K::Punct, K::Conj, K::Subord, K::Noun, K::Verb, K::Noun, K::Punct, K::Prep, K::Verb, K::Noun, K::Prep, K::Prep, K::Punct, K::Verb, K::Noun, K::Prep, K::Punct, K::Conj, K::Verb, K::Noun, K::Noun, K::Conj, K::Noun, K::Punct, K::Subord, K::Noun, K::Verb, K::Adj, K::Prep, K::Prep, K::Punct, K::Verb, K::Noun, K::Verb, K::Punct, K::Conj, K::Adverb, K::Punct, K::Noun, K::Adverb, K::Verb, K::Adverb, K::Noun, K::Verb, K::Noun, K::Adj, K::Prep, K::Punct, K::Noun, K::Verb, K::Prep, K::Prep, K::Prep, K::Verb, K::Noun, K::Prep, K::Punct],
    ),
    (
        &["That", "part", "of", "the", "sea", "known", "among", "whalemen", "as", "the", "\"", "Brazil", "Banks", "\"", "does", "not", "bear", "that", "name", "as", "the", "Banks", "of", "Newfoundland", "do", ",", "because", "of", "there", "being", "shallows", "and", "soundings", "there", ",", "but", "because", "of", "this", "remarkable", "meadow-like", "appearance", ",", "caused", "by", "the", "vast", "drifts", "of", "brit", "continually", "floating", "in", "those", "latitudes", ",", "where", "the", "Right", "Whale", "is", "often", "chased", "."],
        &[Tag::Det, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Verb, Tag::Adp, Tag::Noun, Tag::Adp, Tag::Det, Tag::Punct, Tag::Propn, Tag::Propn, Tag::Punct, Tag::Aux, Tag::Part, Tag::Verb, Tag::Det, Tag::Noun, Tag::Sconj, Tag::Det, Tag::Propn, Tag::Adp, Tag::Propn, Tag::Aux, Tag::Punct, Tag::Adp, Tag::Adp, Tag::Pron, Tag::Aux, Tag::Noun, Tag::Cconj, Tag::Noun, Tag::Adv, Tag::Punct, Tag::Cconj, Tag::Adp, Tag::Adp, Tag::Det, Tag::Adj, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Verb, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Adv, Tag::Verb, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Det, Tag::Adj, Tag::Noun, Tag::Aux, Tag::Adv, Tag::Verb, Tag::Punct],
        &[K::Noun, K::Prep, K::Verb, K::Prep, K::Prep, K::Punct, K::Noun, K::Punct, K::Verb, K::Particle, K::Verb, K::Noun, K::Subord, K::Noun, K::Prep, K::Verb, K::Punct, K::Prep, K::Noun, K::Verb, K::Noun, K::Conj, K::Noun, K::Adverb, K::Punct, K::Conj, K::Prep, K::Noun, K::Punct, K::Verb, K::Prep, K::Prep, K::Adverb, K::Verb, K::Prep, K::Punct, K::Adverb, K::Noun, K::Verb, K::Adverb, K::Verb, K::Punct],
    ),
    (
        &["Already", "has", "it", "been", "related", "how", "the", "great", "leviathan", "is", "afar", "off", "descried", "from", "the", "mast-head", ";", "how", "he", "is", "chased", "over", "the", "watery", "moors", ",", "and", "slaughtered", "in", "the", "valleys", "of", "the", "deep", ";", "how", "he", "is", "then", "towed", "alongside", "and", "beheaded", ";", "and", "how", "(", "on", "the", "principle", "which", "entitled", "the", "headsman", "of", "old", "to", "the", "garments", "in", "which", "the", "beheaded", "was", "killed", ",", "his", "great", "padded", "surtout", "becomes", "the", "property", "of", "his", "executioner", ";", "how", ",", "in", "due", "time", ",", "he", "is", "condemned", "to", "the", "pots", ",", "and", ",", "like", "Shadrach", ",", "Meshach", ",", "and", "Abednego", ",", "his", "spermaceti", ",", "oil", ",", "and", "bone", "pass", "unscathed", "through", "the", "fire", ";", "—", "but", "now", "it", "remains", "to", "conclude", "the", "last", "chapter", "of", "this", "part", "of", "the", "description", "by", "rehearsing", "—", "singing", ",", "if", "I", "may", "—", "the", "romantic", "proceeding", "of", "decanting", "off", "his", "oil", "into", "the", "casks", "and", "striking", "them", "down", "into", "the", "hold", ",", "where", "once", "again", "leviathan", "returns", "to", "his", "native", "profundities", ",", "sliding", "along", "beneath", "the", "surface", "as", "before", ";", "but", ",", "alas", "!"],
        &[Tag::Adv, Tag::Aux, Tag::Pron, Tag::Aux, Tag::Verb, Tag::Adv, Tag::Det, Tag::Adj, Tag::Noun, Tag::Aux, Tag::Adv, Tag::Adv, Tag::Verb, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Pron, Tag::Aux, Tag::Verb, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Verb, Tag::Adp, Tag::Det, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Pron, Tag::Aux, Tag::Adv, Tag::Verb, Tag::Adv, Tag::Cconj, Tag::Verb, Tag::Punct, Tag::Cconj, Tag::Adv, Tag::Punct, Tag::Adp, Tag::Det, Tag::Noun, Tag::Pron, Tag::Verb, Tag::Det, Tag::Noun, Tag::Adp, Tag::Adj, Tag::Adp, Tag::Det, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Det, Tag::Noun, Tag::Aux, Tag::Verb, Tag::Punct, Tag::Pron, Tag::Adj, Tag::Adj, Tag::Noun, Tag::Verb, Tag::Det, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Punct, Tag::Adp, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Pron, Tag::Aux, Tag::Verb, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Punct, Tag::Adp, Tag::Propn, Tag::Punct, Tag::Propn, Tag::Punct, Tag::Cconj, Tag::Propn, Tag::Punct, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Noun, Tag::Verb, Tag::Adj, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Punct, Tag::Cconj, Tag::Adv, Tag::Pron, Tag::Verb, Tag::Part, Tag::Verb, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Adp, Tag::Verb, Tag::Punct, Tag::Verb, Tag::Punct, Tag::Sconj, Tag::Pron, Tag::Aux, Tag::Punct, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Verb, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Cconj, Tag::Verb, Tag::Pron, Tag::Adp, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Adv, Tag::Adv, Tag::Noun, Tag::Verb, Tag::Adp, Tag::Pron, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Verb, Tag::Adv, Tag::Adp, Tag::Det, Tag::Noun, Tag::Sconj, Tag::Adv, Tag::Punct, Tag::Cconj, Tag::Punct, Tag::Intj, Tag::Punct],
        &[K::Adverb, K::Verb, K::Noun, K::Verb, K::Adverb, K::Noun, K::Verb, K::Adverb, K::Verb, K::Prep, K::Punct, K::Adverb, K::Noun, K::Verb, K::Prep, K::Punct, K::Conj, K::Verb, K::Prep, K::Prep, K::Punct, K::Adverb, K::Noun, K::Verb, K::Adverb, K::Verb, K::Adverb, K::Conj, K::Verb, K::Punct, K::Conj, K::Adverb, K::Punct, K::Prep, K::Verb, K::Noun, K::Prep, K::Prep, K::Prep, K::Verb, K::Punct, K::Noun, K::Noun, K::Verb, K::Noun, K::Prep, K::Punct, K::Adverb, K::Punct, K::Prep, K::Punct, K::Noun, K::Verb, K::Prep, K::Punct, K::Conj, K::Punct, K::Prep, K::Punct, K::Noun, K::Punct, K::Conj, K::Noun, K::Punct, K::Noun, K::Punct, K::Noun, K::Punct, K::Conj, K::Noun, K::Verb, K::Adj, K::Prep, K::Punct, K::Conj, K::Adverb, K::Noun, K::Verb, K::Particle, K::Verb, K::Noun, K::Prep, K::Prep, K::Prep, K::Verb, K::Punct, K::Verb, K::Punct, K::Subord, K::Noun, K::Verb, K::Punct, K::Noun, K::Prep, K::Verb, K::Prep, K::Prep, K::Conj, K::Verb, K::Noun, K::Prep, K::Prep, K::Punct, K::Adverb, K::Noun, K::Verb, K::Prep, K::Punct, K::Verb, K::Adverb, K::Prep, K::Subord, K::Adverb, K::Punct, K::Conj, K::Punct, K::Interj, K::Punct],
    ),
    (
        &["Some", "gamesome", "wights", "will", "tell", "you", "that", "they", "have", "to", "plant", "weeds", "there", ",", "they", "do", "n't", "grow", "naturally", ";", "that", "they", "import", "Canada", "thistles", ";", "that", "they", "have", "to", "send", "beyond", "seas", "for", "a", "spile", "to", "stop", "a", "leak", "in", "an", "oil", "cask", ";", "that", "pieces", "of", "wood", "in", "Nantucket", "are", "carried", "about", "like", "bits", "of", "the", "true", "cross", "in", "Rome", ";", "that", "people", "there", "plant", "toadstools", "before", "their", "houses", ",", "to", "get", "under", "the", "shade", "in", "summer", "time", ";", "that", "one", "blade", "of", "grass", "makes", "an", "oasis", ",", "three", "blades", "in", "a", "day", "'s", "walk", "a", "prairie", ";", "that", "they", "wear", "quicksand", "shoes", ",", "something", "like", "Laplander", "snow-shoes", ";", "that", "they", "are", "so", "shut", "up", ",", "belted", ",", "about", ",", "every", "way", "inclosed", "surrounded", ",", "and", "made", "an", "utter", "island", "of", "by", "the", "ocean", ",", "that", "to", "their", "very", "chairs", "and", "tables", "small", "clams", "will", "sometimes", "be", "found", "adhering", ",", "as", "to", "the", "backs", "of", "sea", "turtles", "."],
        &[Tag::Det, Tag::Adj, Tag::Noun, Tag::Aux, Tag::Verb, Tag::Pron, Tag::Sconj, Tag::Pron, Tag::Aux, Tag::Part, Tag::Verb, Tag::Noun, Tag::Adv, Tag::Punct, Tag::Pron, Tag::Aux, Tag::Part, Tag::Verb, Tag::Adv, Tag::Punct, Tag::Sconj, Tag::Pron, Tag::Verb, Tag::Propn, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Pron, Tag::Aux, Tag::Part, Tag::Verb, Tag::Adp, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Part, Tag::Verb, Tag::Det, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Adp, Tag::Propn, Tag::Aux, Tag::Verb, Tag::Adv, Tag::Adp, Tag::Noun, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Propn, Tag::Punct, Tag::Sconj, Tag::Noun, Tag::Adv, Tag::Verb, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Part, Tag::Verb, Tag::Adp, Tag::Det, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Num, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Verb, Tag::Det, Tag::Noun, Tag::Punct, Tag::Num, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Part, Tag::Noun, Tag::Det, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Pron, Tag::Verb, Tag::Noun, Tag::Noun, Tag::Punct, Tag::Pron, Tag::Adp, Tag::Noun, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Pron, Tag::Aux, Tag::Adv, Tag::Verb, Tag::Adp, Tag::Punct, Tag::Verb, Tag::Punct, Tag::Adv, Tag::Punct, Tag::Det, Tag::Noun, Tag::Verb, Tag::Verb, Tag::Punct, Tag::Cconj, Tag::Verb, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Adp, Tag::Pron, Tag::Adj, Tag::Noun, Tag::Cconj, Tag::Noun, Tag::Adj, Tag::Noun, Tag::Aux, Tag::Adv, Tag::Aux, Tag::Verb, Tag::Verb, Tag::Punct, Tag::Sconj, Tag::Adp, Tag::Det, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Noun, Tag::Punct],
        &[K::Noun, K::Verb, K::Noun, K::Subord, K::Noun, K::Verb, K::Particle, K::Verb, K::Noun, K::Adverb, K::Punct, K::Noun, K::Verb, K::Particle, K::Verb, K::Adverb, K::Punct, K::Subord, K::Noun, K::Verb, K::Noun, K::Punct, K::Subord, K::Noun, K::Verb, K::Particle, K::Verb, K::Prep, K::Prep, K::Particle, K::Verb, K::Noun, K::Prep, K::Punct, K::Subord, K::Noun, K::Prep, K::Prep, K::Verb, K::Adverb, K::Prep, K::Prep, K::Prep, K::Punct, K::Subord, K::Noun, K::Adverb, K::Verb, K::Noun, K::Prep, K::Punct, K::Particle, K::Verb, K::Prep, K::Prep, K::Punct, K::Subord, K::Noun, K::Prep, K::Verb, K::Noun, K::Punct, K::Noun, K::Prep, K::Particle, K::Noun, K::Noun, K::Punct, K::Subord, K::Noun, K::Verb, K::Noun, K::Punct, K::Noun, K::Prep, K::Punct, K::Subord, K::Noun, K::Verb, K::Adverb, K::Verb, K::Prep, K::Punct, K::Verb, K::Punct, K::Adverb, K::Punct, K::Noun, K::Verb, K::Punct, K::Conj, K::Verb, K::Noun, K::Prep, K::Prep, K::Punct, K::Subord, K::Prep, K::Conj, K::Noun, K::Noun, K::Verb, K::Adverb, K::Verb, K::Punct, K::Subord, K::Prep, K::Prep, K::Punct],
    ),
    (
        &["And", "now", "that", "at", "the", "proper", "time", "and", "place", ",", "after", "so", "long", "and", "wide", "a", "preliminary", "cruise", ",", "Ahab", ",", "—", "all", "other", "whaling", "waters", "swept", "—", "seemed", "to", "have", "chased", "his", "foe", "into", "an", "ocean-fold", ",", "to", "slay", "him", "the", "more", "securely", "there", ";", "now", ",", "that", "he", "found", "himself", "hard", "by", "the", "very", "latitude", "and", "longitude", "where", "his", "tormenting", "wound", "had", "been", "inflicted", ";", "now", "that", "a", "vessel", "had", "been", "spoken", "which", "on", "the", "very", "day", "preceding", "had", "actually", "encountered", "Moby", "Dick", ";", "—", "and", "now", "that", "all", "his", "successive", "meetings", "with", "various", "ships", "contrastingly", "concurred", "to", "show", "the", "demoniac", "indifference", "with", "which", "the", "white", "whale", "tore", "his", "hunters", ",", "whether", "sinning", "or", "sinned", "against", ";", "now", "it", "was", "that", "there", "lurked", "a", "something", "in", "the", "old", "man", "'s", "eyes", ",", "which", "it", "was", "hardly", "sufferable", "for", "feeble", "souls", "to", "see", "."],
        &[Tag::Cconj, Tag::Adv, Tag::Sconj, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Cconj, Tag::Noun, Tag::Punct, Tag::Adp, Tag::Adv, Tag::Adj, Tag::Cconj, Tag::Adj, Tag::Det, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Propn, Tag::Punct, Tag::Punct, Tag::Det, Tag::Adj, Tag::Noun, Tag::Noun, Tag::Verb, Tag::Punct, Tag::Verb, Tag::Part, Tag::Aux, Tag::Verb, Tag::Pron, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Part, Tag::Verb, Tag::Pron, Tag::Det, Tag::Adv, Tag::Adv, Tag::Adv, Tag::Punct, Tag::Adv, Tag::Punct, Tag::Sconj, Tag::Pron, Tag::Verb, Tag::Pron, Tag::Adv, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Cconj, Tag::Noun, Tag::Adv, Tag::Pron, Tag::Adj, Tag::Noun, Tag::Aux, Tag::Aux, Tag::Verb, Tag::Punct, Tag::Adv, Tag::Sconj, Tag::Det, Tag::Noun, Tag::Aux, Tag::Aux, Tag::Verb, Tag::Pron, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adj, Tag::Aux, Tag::Adv, Tag::Verb, Tag::Propn, Tag::Propn, Tag::Punct, Tag::Punct, Tag::Cconj, Tag::Adv, Tag::Sconj, Tag::Det, Tag::Pron, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Adj, Tag::Noun, Tag::Adv, Tag::Verb, Tag::Part, Tag::Verb, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Det, Tag::Adj, Tag::Noun, Tag::Verb, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Verb, Tag::Cconj, Tag::Verb, Tag::Adp, Tag::Punct, Tag::Adv, Tag::Pron, Tag::Aux, Tag::Sconj, Tag::Pron, Tag::Verb, Tag::Det, Tag::Pron, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Part, Tag::Noun, Tag::Punct, Tag::Pron, Tag::Pron, Tag::Aux, Tag::Adv, Tag::Adj, Tag::Adp, Tag::Adj, Tag::Noun, Tag::Part, Tag::Verb, Tag::Punct],
        &[K::Conj, K::Adverb, K::Subord, K::Prep, K::Conj, K::Noun, K::Punct, K::Prep, K::Adverb, K::Adj, K::Conj, K::Noun, K::Punct, K::Noun, K::Punct, K::Noun, K::Verb, K::Punct, K::Verb, K::Particle, K::Verb, K::Noun, K::Prep, K::Punct, K::Particle, K::Verb, K::Noun, K::Noun, K::Adverb, K::Punct, K::Adverb, K::Punct, K::Subord, K::Noun, K::Verb, K::Noun, K::Adverb, K::Prep, K::Conj, K::Noun, K::Adverb, K::Noun, K::Noun, K::Verb, K::Punct, K::Adverb, K::Subord, K::Noun, K::Verb, K::Noun, K::Prep, K::Verb, K::Adverb, K::Verb, K::Noun, K::Punct, K::Conj, K::Adverb, K::Subord, K::Noun, K::Noun, K::Prep, K::Adverb, K::Verb, K::Particle, K::Verb, K::Noun, K::Prep, K::Verb, K::Noun, K::Punct, K::Subord, K::Verb, K::Conj, K::Verb, K::Prep, K::Punct, K::Adverb, K::Noun, K::Verb, K::Subord, K::Noun, K::Verb, K::Noun, K::Prep, K::Particle, K::Noun, K::Punct, K::Noun, K::Noun, K::Verb, K::Adverb, K::Adj, K::Prep, K::Particle, K::Verb, K::Punct],
    ),
    (
        &["Nor", ",", "at", "any", "time", ",", "by", "night", "or", "day", "could", "the", "mariners", "now", "step", "upon", "the", "deck", ",", "unless", "Ahab", "was", "before", "them", ";", "either", "standing", "in", "his", "pivot-hole", ",", "or", "exactly", "pacing", "the", "planks", "between", "two", "undeviating", "limits", ",", "—", "the", "main-mast", "and", "the", "mizen", ",", "—", "or", "else", "they", "saw", "him", "standing", "in", "the", "cabin-scuttle", ",", "—", "his", "living", "foot", "advanced", "upon", "the", "deck", ",", "as", "if", "to", "step", ";", "his", "hat", "slouched", "heavily", "over", "his", "eyes", ";", "so", "that", "however", "motionless", "he", "stood", ",", "however", "the", "days", "and", "nights", "were", "added", "on", ",", "that", "he", "had", "not", "swung", "in", "his", "hammock", ";", "yet", "hidden", "beneath", "that", "slouching", "hat", ",", "they", "could", "never", "tell", "unerringly", "whether", ",", "for", "all", "this", ",", "his", "eyes", "were", "really", "closed", "at", "times", ";", "or", "whether", "he", "was", "still", "intently", "scanning", ";", "no", "matter", ",", "though", "he", "stood", "so", "in", "the", "scuttle", "for", "a", "whole", "hour", "on", "the", "stretch", ",", "and", "the", "unheeded", "night-damp", "collected", "in", "beads", "of", "dew", "upon", "that", "stone-carved", "coat", "and", "hat", "."],
        &[Tag::Cconj, Tag::Punct, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Adp, Tag::Noun, Tag::Cconj, Tag::Noun, Tag::Aux, Tag::Det, Tag::Noun, Tag::Adv, Tag::Verb, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Propn, Tag::Aux, Tag::Adp, Tag::Pron, Tag::Punct, Tag::Adv, Tag::Verb, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Adv, Tag::Verb, Tag::Det, Tag::Noun, Tag::Adp, Tag::Num, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Punct, Tag::Det, Tag::Noun, Tag::Cconj, Tag::Det, Tag::Noun, Tag::Punct, Tag::Punct, Tag::Cconj, Tag::Adv, Tag::Pron, Tag::Verb, Tag::Pron, Tag::Verb, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Punct, Tag::Pron, Tag::Adj, Tag::Noun, Tag::Verb, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Sconj, Tag::Part, Tag::Verb, Tag::Punct, Tag::Pron, Tag::Noun, Tag::Verb, Tag::Adv, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Sconj, Tag::Adv, Tag::Adj, Tag::Pron, Tag::Verb, Tag::Punct, Tag::Adv, Tag::Det, Tag::Noun, Tag::Cconj, Tag::Noun, Tag::Aux, Tag::Verb, Tag::Adp, Tag::Punct, Tag::Sconj, Tag::Pron, Tag::Aux, Tag::Part, Tag::Verb, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Adj, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Pron, Tag::Aux, Tag::Adv, Tag::Verb, Tag::Adv, Tag::Sconj, Tag::Punct, Tag::Adp, Tag::Det, Tag::Det, Tag::Punct, Tag::Pron, Tag::Noun, Tag::Aux, Tag::Adv, Tag::Verb, Tag::Adp, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Sconj, Tag::Pron, Tag::Aux, Tag::Adv, Tag::Adv, Tag::Verb, Tag::Punct, Tag::Det, Tag::Noun, Tag::Punct, Tag::Sconj, Tag::Pron, Tag::Verb, Tag::Adv, Tag::Adp, Tag::Det, Tag::Noun, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Det, Tag::Adj, Tag::Noun, Tag::Verb, Tag::Adp, Tag::Noun, Tag::Adp, Tag::Noun, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Cconj, Tag::Noun, Tag::Punct],
        &[K::Conj, K::Punct, K::Prep, K::Punct, K::Prep, K::Conj, K::Noun, K::Verb, K::Noun, K::Adverb, K::Verb, K::Prep, K::Punct, K::Subord, K::Noun, K::Verb, K::Prep, K::Punct, K::Adverb, K::Verb, K::Prep, K::Punct, K::Conj, K::Adverb, K::Verb, K::Noun, K::Prep, K::Punct, K::Noun, K::Conj, K::Noun, K::Punct, K::Conj, K::Adverb, K::Noun, K::Verb, K::Noun, K::Verb, K::Prep, K::Punct, K::Noun, K::Noun, K::Verb, K::Prep, K::Punct, K::Subord, K::Particle, K::Verb, K::Punct, K::Noun, K::Verb, K::Adverb, K::Prep, K::Punct, K::Subord, K::Adverb, K::Noun, K::Verb, K::Punct, K::Adverb, K::Noun, K::Conj, K::Noun, K::Verb, K::Prep, K::Punct, K::Subord, K::Noun, K::Verb, K::Particle, K::Verb, K::Prep, K::Punct, K::Conj, K::Adj, K::Prep, K::Punct, K::Noun, K::Verb, K::Adverb, K::Verb, K::Adverb, K::Subord, K::Punct, K::Prep, K::Punct, K::Noun, K::Verb, K::Adverb, K::Verb, K::Prep, K::Punct, K::Conj, K::Subord, K::Noun, K::Verb, K::Adverb, K::Verb, K::Punct, K::Noun, K::Punct, K::Subord, K::Noun, K::Verb, K::Adverb, K::Prep, K::Prep, K::Prep, K::Punct, K::Conj, K::Noun, K::Verb, K::Prep, K::Prep, K::Prep, K::Conj, K::Noun, K::Punct],
    ),
    (
        &["For", "loath", "to", "depart", ",", "yet", ";", "very", "loath", "to", "leave", ",", "for", "good", ",", "a", "ship", "bound", "on", "so", "long", "and", "perilous", "a", "voyage", "—", "beyond", "both", "stormy", "Capes", ",", "a", "ship", "in", "which", "some", "thousands", "of", "his", "hard", "earned", "dollars", "were", "invested", ";", "a", "ship", ",", "in", "which", "an", "old", "shipmate", "sailed", "as", "captain", ",", "a", "man", "almost", "as", "old", "as", "he", ",", "once", "more", "starting", "to", "encounter", "all", "the", "terrors", "of", "the", "pitiless", "jaw", ";", "loath", "to", "say", "good-bye", "to", "a", "thing", "so", "every", "way", "brimful", "of", "every", "interest", "to", "him", ",", "—", "poor", "old", "Bildad", "lingered", "long", ";", "paced", "the", "deck", "with", "anxious", "strides", ";", "ran", "down", "into", "the", "cabin", "to", "speak", "another", "farewell", "word", "there", ";", "again", "came", "on", "deck", ",", "and", "looked", "to", "windward", ",", "looked", "towards", "the", "wide", "and", "endless", "waters", ",", "only", "bounded", "by", "the", "far-off", "unseen", "Eastern", "Continents", ";", "looked", "towards", "the", "land", ";", "looked", "aloft", ";", "looked", "right", "and", "left", ";", "looked", "everywhere", "and", "nowhere", ";", "and", "at", "last", ",", "mechanically", "coiling", "a", "rope", "upon", "its", "pin", ",", "convulsively", "grasped", "stout", "Peleg", "by", "the", "hand", ",", "and", "holding", "up", "a", "lantern", ",", "for", "a", "moment", "stood", "gazing", "heroically", "in", "his", "face", ",", "as", "much", "as", "to", "say", ",", "\"", "Nevertheless", ",", "friend", "Peleg", ",", "I", "can", "stand", "it", ";", "yes", ",", "I", "can", ".", "\""],
        &[Tag::Adp, Tag::Adj, Tag::Part, Tag::Verb, Tag::Punct, Tag::Adv, Tag::Punct, Tag::Adv, Tag::Adj, Tag::Part, Tag::Verb, Tag::Punct, Tag::Adp, Tag::Noun, Tag::Punct, Tag::Det, Tag::Noun, Tag::Adj, Tag::Adp, Tag::Adv, Tag::Adj, Tag::Cconj, Tag::Adj, Tag::Det, Tag::Noun, Tag::Punct, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Det, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Det, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Adj, Tag::Adj, Tag::Noun, Tag::Aux, Tag::Verb, Tag::Punct, Tag::Det, Tag::Noun, Tag::Punct, Tag::Adp, Tag::Pron, Tag::Det, Tag::Adj, Tag::Noun, Tag::Verb, Tag::Adp, Tag::Noun, Tag::Punct, Tag::Det, Tag::Noun, Tag::Adv, Tag::Adv, Tag::Adj, Tag::Sconj, Tag::Pron, Tag::Punct, Tag::Adv, Tag::Adv, Tag::Verb, Tag::Part, Tag::Verb, Tag::Det, Tag::Det, Tag::Noun, Tag::Adp, Tag::Det, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Adj, Tag::Part, Tag::Verb, Tag::Noun, Tag::Adp, Tag::Det, Tag::Noun, Tag::Adv, Tag::Det, Tag::Noun, Tag::Adj, Tag::Adp, Tag::Det, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Punct, Tag::Punct, Tag::Adj, Tag::Adj, Tag::Propn, Tag::Verb, Tag::Adv, Tag::Punct, Tag::Verb, Tag::Det, Tag::Noun, Tag::Adp, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Verb, Tag::Adp, Tag::Adp, Tag::Det, Tag::Noun, Tag::Part, Tag::Verb, Tag::Det, Tag::Noun, Tag::Noun, Tag::Adv, Tag::Punct, Tag::Adv, Tag::Verb, Tag::Adp, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Verb, Tag::Adp, Tag::Noun, Tag::Punct, Tag::Verb, Tag::Adp, Tag::Det, Tag::Adj, Tag::Cconj, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Verb, Tag::Adp, Tag::Det, Tag::Adj, Tag::Adj, Tag::Adj, Tag::Noun, Tag::Punct, Tag::Verb, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Verb, Tag::Adv, Tag::Punct, Tag::Verb, Tag::Adv, Tag::Cconj, Tag::Adv, Tag::Punct, Tag::Verb, Tag::Adv, Tag::Cconj, Tag::Adv, Tag::Punct, Tag::Cconj, Tag::Adp, Tag::Adj, Tag::Punct, Tag::Adv, Tag::Verb, Tag::Det, Tag::Noun, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Verb, Tag::Adj, Tag::Propn, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Cconj, Tag::Verb, Tag::Adp, Tag::Det, Tag::Noun, Tag::Punct, Tag::Adp, Tag::Det, Tag::Noun, Tag::Verb, Tag::Verb, Tag::Adv, Tag::Adp, Tag::Pron, Tag::Noun, Tag::Punct, Tag::Adv, Tag::Adv, Tag::Sconj, Tag::Part, Tag::Verb, Tag::Punct, Tag::Punct, Tag::Adv, Tag::Punct, Tag::Noun, Tag::Propn, Tag::Punct, Tag::Pron, Tag::Aux, Tag::Verb, Tag::Pron, Tag::Punct, Tag::Intj, Tag::Punct, Tag::Pron, Tag::Aux, Tag::Punct, Tag::Punct],
        &[K::Prep, K::Particle, K::Verb, K::Punct, K::Adverb, K::Punct, K::Adverb, K::Adj, K::Particle, K::Verb, K::Punct, K::Prep, K::Punct, K::Noun, K::Adj, K::Prep, K::Adverb, K::Adj, K::Conj, K::Noun, K::Punct, K::Prep, K::Punct, K::Noun, K::Prep, K::Prep, K::Verb, K::Punct, K::Noun, K::Punct, K::Prep, K::Verb, K::Prep, K::Punct, K::Noun, K::Adverb, K::Adj, K::Subord, K::Noun, K::Punct, K::Adverb, K::Verb, K::Particle, K::Verb, K::Noun, K::Prep, K::Punct, K::Adj, K::Particle, K::Verb, K::Noun, K::Prep, K::Adverb, K::Noun, K::Adj, K::Prep, K::Prep, K::Punct, K::Noun, K::Verb, K::Adverb, K::Punct, K::Verb, K::Noun, K::Prep, K::Punct, K::Verb, K::Prep, K::Prep, K::Particle, K::Verb, K::Noun, K::Adverb, K::Punct, K::Adverb, K::Verb, K::Prep, K::Punct, K::Conj, K::Verb, K::Prep, K::Punct, K::Verb, K::Prep, K::Conj, K::Noun, K::Punct, K::Adverb, K::Verb, K::Prep, K::Punct, K::Verb, K::Prep, K::Punct, K::Verb, K::Adverb, K::Punct, K::Verb, K::Adverb, K::Conj, K::Adverb, K::Punct, K::Verb, K::Adverb, K::Conj, K::Adverb, K::Punct, K::Conj, K::Prep, K::Punct, K::Adverb, K::Verb, K::Noun, K::Prep, K::Punct, K::Adverb, K::Verb, K::Noun, K::Prep, K::Punct, K::Conj, K::Verb, K::Prep, K::Punct, K::Prep, K::Verb, K::Adverb, K::Prep, K::Punct, K::Adverb, K::Subord, K::Particle, K::Verb, K::Punct, K::Adverb, K::Punct, K::Noun, K::Punct, K::Noun, K::Verb, K::Noun, K::Punct, K::Interj, K::Punct, K::Noun, K::Verb, K::Punct],
    ),
];

fn pieces(words: &[&str], tags: &[Tag]) -> Vec<(String, Tag)> {
    words
        .iter()
        .map(|w| w.to_string())
        .zip(tags.iter().copied())
        .collect()
}

fn token_kinds(chunks: &[english_chunk::Chunk], len: usize) -> Vec<ChunkKind> {
    let mut out = Vec::with_capacity(len);
    for c in chunks {
        for _ in c.span() {
            out.push(c.kind());
        }
    }
    debug_assert_eq!(out.len(), len, "chunks must tile the input");
    out
}

#[test]
fn hard_rule_chunks() {
    assert_eq!(SENTENCES.len(), 10);
    for (si, (words, tags, want)) in SENTENCES.iter().enumerate() {
        assert_eq!(words.len(), tags.len(), "sentence {si}: words/tags length");
        let input = pieces(words, tags);
        let got: Vec<ChunkKind> = chunk_tagged(&input).iter().map(|c| c.kind()).collect();
        assert_eq!(got, *want, "sentence {si}");
    }
}

#[test]
fn hard_end_to_end() {
    let model = Model::from_json(include_str!("../../english-pos/weights/upos.json")).unwrap();
    let flat: Vec<&str> = SENTENCES
        .iter()
        .flat_map(|(w, _, _)| w.iter().copied())
        .collect();
    let surf: Vec<String> = flat.iter().map(|s| s.to_string()).collect();
    let mut tagged = model.tag_beam_margins(&surf);
    english_pos::apply_rules(&surf, &mut tagged, english_pos::RULES);
    let tags: Vec<Tag> = tagged.iter().map(|(t, _)| *t).collect();
    // NOTE: end-to-end here runs the shipped pipeline (beam +
    // rules), unlike the tagger evals which pin the raw model.
    let mut sent_match = 0;
    let (mut tok_match, mut tok_total) = (0usize, 0usize);
    let mut miss_sentences = Vec::new();
    let mut off = 0;
    for (si, (words, gold_tags, want)) in SENTENCES.iter().enumerate() {
        let n = words.len();
        let tagged: Vec<(String, Tag)> = words
            .iter()
            .map(|w| w.to_string())
            .zip(tags[off..off + n].iter().copied())
            .collect();
        let gold = pieces(words, gold_tags);
        let got_chunks = chunk_tagged(&tagged);
        let gold_chunks = chunk_tagged(&gold);
        let got: Vec<ChunkKind> = got_chunks.iter().map(|c| c.kind()).collect();
        if got == *want {
            sent_match += 1;
        } else {
            miss_sentences.push(si);
        }
        for (g, t) in token_kinds(&gold_chunks, n)
            .iter()
            .zip(token_kinds(&got_chunks, n).iter())
        {
            tok_total += 1;
            if g == t {
                tok_match += 1;
            }
        }
        off += n;
    }
    let sent_rate = sent_match as f64 / SENTENCES.len() as f64;
    let tok_rate = tok_match as f64 / tok_total as f64;
    eprintln!(
        "hard chunk end-to-end: {sent_match}/{} sentences exact ({sent_rate:.3}), token chunk-kind {tok_match}/{tok_total} ({tok_rate:.3}), miss sentences {miss_sentences:?}",
        SENTENCES.len(),
    );
    // Sentence-exact saturates at 0 on hard text (every sentence
    // carries tag misses); token-kind is the moving metric (note it
    // runs ABOVE tag accuracy — chunking absorbs some tag errors).
    assert!(
        tok_rate >= 0.87,
        "hard chunk end-to-end token rate {tok_rate:.3} below bar; move deliberately",
    );
}
