/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 34
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 5
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__sentence_end_token1 = 1,
  aux_sym__sentence_end_token2 = 2,
  aux_sym__sentence_end_token3 = 3,
  sym_paragraph_break = 4,
  anon_sym_COMMA = 5,
  sym_semicolon = 6,
  sym_colon = 7,
  sym_em_dash = 8,
  sym__quote = 9,
  sym_dotted = 10,
  sym_number = 11,
  sym__end_dot = 12,
  sym_period = 13,
  sym_word = 14,
  sym_conjunction = 15,
  sym_subordinator = 16,
  sym_source_file = 17,
  sym_paragraph = 18,
  sym_sentence = 19,
  sym__sentence_end = 20,
  sym_clause = 21,
  sym_subordinate_clause = 22,
  sym__comma = 23,
  sym__wordish = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_source_file_repeat2 = 26,
  aux_sym_paragraph_repeat1 = 27,
  aux_sym_sentence_repeat1 = 28,
  aux_sym__sentence_end_repeat1 = 29,
  aux_sym_clause_repeat1 = 30,
  aux_sym_subordinate_clause_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__sentence_end_token1] = "_sentence_end_token1",
  [aux_sym__sentence_end_token2] = "_sentence_end_token2",
  [aux_sym__sentence_end_token3] = "_sentence_end_token3",
  [sym_paragraph_break] = "paragraph_break",
  [anon_sym_COMMA] = ",",
  [sym_semicolon] = "semicolon",
  [sym_colon] = "colon",
  [sym_em_dash] = "em_dash",
  [sym__quote] = "_quote",
  [sym_dotted] = "dotted",
  [sym_number] = "number",
  [sym__end_dot] = "_end_dot",
  [sym_period] = "period",
  [sym_word] = "word",
  [sym_conjunction] = "conjunction",
  [sym_subordinator] = "subordinator",
  [sym_source_file] = "source_file",
  [sym_paragraph] = "paragraph",
  [sym_sentence] = "sentence",
  [sym__sentence_end] = "_sentence_end",
  [sym_clause] = "clause",
  [sym_subordinate_clause] = "subordinate_clause",
  [sym__comma] = "_comma",
  [sym__wordish] = "_wordish",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_sentence_repeat1] = "sentence_repeat1",
  [aux_sym__sentence_end_repeat1] = "_sentence_end_repeat1",
  [aux_sym_clause_repeat1] = "clause_repeat1",
  [aux_sym_subordinate_clause_repeat1] = "subordinate_clause_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__sentence_end_token1] = aux_sym__sentence_end_token1,
  [aux_sym__sentence_end_token2] = aux_sym__sentence_end_token2,
  [aux_sym__sentence_end_token3] = aux_sym__sentence_end_token3,
  [sym_paragraph_break] = sym_paragraph_break,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_semicolon] = sym_semicolon,
  [sym_colon] = sym_colon,
  [sym_em_dash] = sym_em_dash,
  [sym__quote] = sym__quote,
  [sym_dotted] = sym_dotted,
  [sym_number] = sym_number,
  [sym__end_dot] = sym__end_dot,
  [sym_period] = sym_period,
  [sym_word] = sym_word,
  [sym_conjunction] = sym_conjunction,
  [sym_subordinator] = sym_subordinator,
  [sym_source_file] = sym_source_file,
  [sym_paragraph] = sym_paragraph,
  [sym_sentence] = sym_sentence,
  [sym__sentence_end] = sym__sentence_end,
  [sym_clause] = sym_clause,
  [sym_subordinate_clause] = sym_subordinate_clause,
  [sym__comma] = sym__comma,
  [sym__wordish] = sym__wordish,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_sentence_repeat1] = aux_sym_sentence_repeat1,
  [aux_sym__sentence_end_repeat1] = aux_sym__sentence_end_repeat1,
  [aux_sym_clause_repeat1] = aux_sym_clause_repeat1,
  [aux_sym_subordinate_clause_repeat1] = aux_sym_subordinate_clause_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__sentence_end_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sentence_end_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sentence_end_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_paragraph_break] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_semicolon] = {
    .visible = true,
    .named = true,
  },
  [sym_colon] = {
    .visible = true,
    .named = true,
  },
  [sym_em_dash] = {
    .visible = true,
    .named = true,
  },
  [sym__quote] = {
    .visible = false,
    .named = true,
  },
  [sym_dotted] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym__end_dot] = {
    .visible = false,
    .named = true,
  },
  [sym_period] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_conjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_subordinator] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym__sentence_end] = {
    .visible = false,
    .named = true,
  },
  [sym_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_subordinate_clause] = {
    .visible = true,
    .named = true,
  },
  [sym__comma] = {
    .visible = false,
    .named = true,
  },
  [sym__wordish] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sentence_end_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subordinate_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 5,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 15,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        ',', 19,
        ':', 21,
        ';', 20,
        '!', 14,
        '?', 14,
        0x2013, 22,
        0x2014, 22,
        ')', 16,
        ']', 16,
        '}', 16,
        '"', 15,
        '\'', 15,
        0x2018, 15,
        0x2019, 15,
        0x201c, 15,
        0x201d, 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ',') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ',') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead == 0x0b ||
          lookahead == '\f') SKIP(1);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == ')' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == ')' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead == 0x0b ||
          lookahead == '\f') SKIP(4);
      if (lookahead == ')' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(16);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        ',', 19,
        ':', 21,
        ';', 20,
        '!', 14,
        '?', 14,
        0x2013, 22,
        0x2014, 22,
        '"', 23,
        '\'', 23,
        0x2018, 23,
        0x2019, 23,
        0x201c, 23,
        0x201d, 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 10:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ',') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(11);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == ')' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(12);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym__sentence_end_token1);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym__sentence_end_token2);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym__sentence_end_token3);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_paragraph_break);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_paragraph_break);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_semicolon);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_colon);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_em_dash);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__quote);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_dotted);
      if (lookahead == '.') ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_dotted);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 11, .external_lex_state = 2},
  [2] = {.lex_state = 11, .external_lex_state = 2},
  [3] = {.lex_state = 11, .external_lex_state = 2},
  [4] = {.lex_state = 11, .external_lex_state = 2},
  [5] = {.lex_state = 7, .external_lex_state = 1},
  [6] = {.lex_state = 11, .external_lex_state = 2},
  [7] = {.lex_state = 7, .external_lex_state = 1},
  [8] = {.lex_state = 11, .external_lex_state = 2},
  [9] = {.lex_state = 7, .external_lex_state = 1},
  [10] = {.lex_state = 7, .external_lex_state = 1},
  [11] = {.lex_state = 11, .external_lex_state = 2},
  [12] = {.lex_state = 11, .external_lex_state = 2},
  [13] = {.lex_state = 7, .external_lex_state = 1},
  [14] = {.lex_state = 7, .external_lex_state = 2},
  [15] = {.lex_state = 7, .external_lex_state = 3},
  [16] = {.lex_state = 12, .external_lex_state = 2},
  [17] = {.lex_state = 12, .external_lex_state = 2},
  [18] = {.lex_state = 12, .external_lex_state = 2},
  [19] = {.lex_state = 7, .external_lex_state = 3},
  [20] = {.lex_state = 0, .external_lex_state = 4},
  [21] = {.lex_state = 11, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 4},
  [23] = {.lex_state = 11, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 4},
  [25] = {.lex_state = 11, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 4},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__sentence_end_token1] = ACTIONS(1),
    [aux_sym__sentence_end_token2] = ACTIONS(1),
    [aux_sym__sentence_end_token3] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_semicolon] = ACTIONS(1),
    [sym_colon] = ACTIONS(1),
    [sym_em_dash] = ACTIONS(1),
    [sym__quote] = ACTIONS(1),
    [sym_dotted] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym__end_dot] = ACTIONS(1),
    [sym_period] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_conjunction] = ACTIONS(1),
    [sym_subordinator] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(33),
    [sym_paragraph] = STATE(28),
    [sym_sentence] = STATE(11),
    [sym_clause] = STATE(20),
    [sym_subordinate_clause] = STATE(20),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [aux_sym_clause_repeat1] = STATE(10),
    [sym_paragraph_break] = ACTIONS(3),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym__quote] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_paragraph] = STATE(32),
    [sym_sentence] = STATE(11),
    [sym_clause] = STATE(20),
    [sym_subordinate_clause] = STATE(20),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(21),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [aux_sym_clause_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_paragraph_break] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym__quote] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym_paragraph] = STATE(32),
    [sym_sentence] = STATE(11),
    [sym_clause] = STATE(20),
    [sym_subordinate_clause] = STATE(20),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(21),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [aux_sym_clause_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_paragraph_break] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym__quote] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(4)] = {
    [sym_paragraph] = STATE(32),
    [sym_sentence] = STATE(11),
    [sym_clause] = STATE(20),
    [sym_subordinate_clause] = STATE(20),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(21),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [aux_sym_clause_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_paragraph_break] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym__quote] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(5)] = {
    [sym_subordinate_clause] = STATE(7),
    [sym__comma] = STATE(7),
    [sym__wordish] = STATE(7),
    [aux_sym_subordinate_clause_repeat1] = STATE(7),
    [aux_sym__sentence_end_token1] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_semicolon] = ACTIONS(19),
    [sym_colon] = ACTIONS(19),
    [sym_em_dash] = ACTIONS(19),
    [sym__quote] = ACTIONS(21),
    [sym_dotted] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym__end_dot] = ACTIONS(19),
    [sym_period] = ACTIONS(21),
    [sym_word] = ACTIONS(21),
    [sym_conjunction] = ACTIONS(19),
    [sym_subordinator] = ACTIONS(19),
  },
  [STATE(6)] = {
    [sym_paragraph] = STATE(31),
    [sym_sentence] = STATE(11),
    [sym_clause] = STATE(20),
    [sym_subordinate_clause] = STATE(20),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(21),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [aux_sym_clause_repeat1] = STATE(10),
    [sym_paragraph_break] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym__quote] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(7)] = {
    [sym_subordinate_clause] = STATE(7),
    [sym__comma] = STATE(7),
    [sym__wordish] = STATE(7),
    [aux_sym_subordinate_clause_repeat1] = STATE(7),
    [aux_sym__sentence_end_token1] = ACTIONS(23),
    [anon_sym_COMMA] = ACTIONS(25),
    [sym_semicolon] = ACTIONS(23),
    [sym_colon] = ACTIONS(23),
    [sym_em_dash] = ACTIONS(23),
    [sym__quote] = ACTIONS(25),
    [sym_dotted] = ACTIONS(25),
    [sym_number] = ACTIONS(25),
    [sym__end_dot] = ACTIONS(23),
    [sym_period] = ACTIONS(25),
    [sym_word] = ACTIONS(25),
    [sym_conjunction] = ACTIONS(25),
    [sym_subordinator] = ACTIONS(28),
  },
  [STATE(8)] = {
    [sym_paragraph] = STATE(32),
    [sym_sentence] = STATE(11),
    [sym_clause] = STATE(20),
    [sym_subordinate_clause] = STATE(20),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(21),
    [aux_sym_paragraph_repeat1] = STATE(11),
    [aux_sym_clause_repeat1] = STATE(10),
    [sym_paragraph_break] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym__quote] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(9)] = {
    [sym_subordinate_clause] = STATE(7),
    [sym__comma] = STATE(7),
    [sym__wordish] = STATE(7),
    [aux_sym_subordinate_clause_repeat1] = STATE(7),
    [aux_sym__sentence_end_token1] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(19),
    [sym_semicolon] = ACTIONS(19),
    [sym_colon] = ACTIONS(19),
    [sym_em_dash] = ACTIONS(19),
    [sym__quote] = ACTIONS(19),
    [sym_dotted] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
    [sym__end_dot] = ACTIONS(19),
    [sym_period] = ACTIONS(19),
    [sym_word] = ACTIONS(19),
    [sym_conjunction] = ACTIONS(19),
    [sym_subordinator] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    STATE(13), 3,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(33), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
    ACTIONS(31), 7,
      sym__end_dot,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [23] = 7,
    ACTIONS(9), 1,
      sym_subordinator,
    ACTIONS(7), 2,
      sym_period,
      sym_word,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      sym_paragraph_break,
    STATE(12), 2,
      sym_sentence,
      aux_sym_paragraph_repeat1,
    STATE(20), 2,
      sym_clause,
      sym_subordinate_clause,
    STATE(10), 3,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(5), 4,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
  [54] = 7,
    ACTIONS(45), 1,
      sym_subordinator,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      sym_paragraph_break,
    ACTIONS(42), 2,
      sym_period,
      sym_word,
    STATE(12), 2,
      sym_sentence,
      aux_sym_paragraph_repeat1,
    STATE(20), 2,
      sym_clause,
      sym_subordinate_clause,
    STATE(10), 3,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(39), 4,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
  [85] = 3,
    STATE(13), 3,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(50), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
    ACTIONS(48), 7,
      sym__end_dot,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [108] = 4,
    ACTIONS(9), 1,
      sym_subordinator,
    STATE(26), 2,
      sym_clause,
      sym_subordinate_clause,
    STATE(10), 3,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(7), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
  [129] = 3,
    ACTIONS(55), 1,
      sym_subordinator,
    STATE(5), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(53), 7,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
  [148] = 4,
    STATE(17), 1,
      aux_sym__sentence_end_repeat1,
    ACTIONS(59), 2,
      aux_sym__sentence_end_token2,
      aux_sym__sentence_end_token3,
    ACTIONS(61), 4,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
    ACTIONS(57), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [169] = 4,
    STATE(18), 1,
      aux_sym__sentence_end_repeat1,
    ACTIONS(65), 2,
      aux_sym__sentence_end_token2,
      aux_sym__sentence_end_token3,
    ACTIONS(67), 4,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
    ACTIONS(63), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [190] = 4,
    STATE(18), 1,
      aux_sym__sentence_end_repeat1,
    ACTIONS(71), 2,
      aux_sym__sentence_end_token2,
      aux_sym__sentence_end_token3,
    ACTIONS(74), 4,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
    ACTIONS(69), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [211] = 3,
    ACTIONS(55), 1,
      sym_subordinator,
    STATE(9), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(76), 7,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
  [230] = 5,
    ACTIONS(9), 1,
      sym_subordinator,
    STATE(23), 1,
      sym__sentence_end,
    ACTIONS(78), 2,
      sym__end_dot,
      aux_sym__sentence_end_token1,
    STATE(22), 2,
      sym_subordinate_clause,
      aux_sym_sentence_repeat1,
    ACTIONS(80), 4,
      sym_conjunction,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [251] = 4,
    ACTIONS(84), 1,
      sym_paragraph_break,
    STATE(21), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(82), 4,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
    ACTIONS(87), 4,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
  [270] = 5,
    ACTIONS(9), 1,
      sym_subordinator,
    STATE(25), 1,
      sym__sentence_end,
    ACTIONS(78), 2,
      sym__end_dot,
      aux_sym__sentence_end_token1,
    STATE(24), 2,
      sym_subordinate_clause,
      aux_sym_sentence_repeat1,
    ACTIONS(80), 4,
      sym_conjunction,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [291] = 2,
    ACTIONS(91), 4,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
    ACTIONS(89), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [305] = 4,
    ACTIONS(98), 1,
      sym_subordinator,
    ACTIONS(93), 2,
      sym__end_dot,
      aux_sym__sentence_end_token1,
    STATE(24), 2,
      sym_subordinate_clause,
      aux_sym_sentence_repeat1,
    ACTIONS(95), 4,
      sym_conjunction,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [323] = 2,
    ACTIONS(103), 4,
      anon_sym_COMMA,
      sym__quote,
      sym_dotted,
      sym_number,
    ACTIONS(101), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [337] = 1,
    ACTIONS(93), 7,
      sym__end_dot,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [347] = 4,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 1,
      sym_paragraph_break,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(29), 1,
      aux_sym_source_file_repeat2,
  [360] = 4,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 1,
      sym_paragraph_break,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(30), 1,
      aux_sym_source_file_repeat2,
  [373] = 4,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 1,
      sym_paragraph_break,
    STATE(8), 1,
      aux_sym_source_file_repeat1,
    STATE(29), 1,
      aux_sym_source_file_repeat2,
  [386] = 4,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 1,
      sym_paragraph_break,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(29), 1,
      aux_sym_source_file_repeat2,
  [399] = 4,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 1,
      sym_paragraph_break,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(27), 1,
      aux_sym_source_file_repeat2,
  [412] = 1,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [417] = 1,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 23,
  [SMALL_STATE(12)] = 54,
  [SMALL_STATE(13)] = 85,
  [SMALL_STATE(14)] = 108,
  [SMALL_STATE(15)] = 129,
  [SMALL_STATE(16)] = 148,
  [SMALL_STATE(17)] = 169,
  [SMALL_STATE(18)] = 190,
  [SMALL_STATE(19)] = 211,
  [SMALL_STATE(20)] = 230,
  [SMALL_STATE(21)] = 251,
  [SMALL_STATE(22)] = 270,
  [SMALL_STATE(23)] = 291,
  [SMALL_STATE(24)] = 305,
  [SMALL_STATE(25)] = 323,
  [SMALL_STATE(26)] = 337,
  [SMALL_STATE(27)] = 347,
  [SMALL_STATE(28)] = 360,
  [SMALL_STATE(29)] = 373,
  [SMALL_STATE(30)] = 386,
  [SMALL_STATE(31)] = 399,
  [SMALL_STATE(32)] = 412,
  [SMALL_STATE(33)] = 417,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subordinate_clause, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subordinate_clause_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subordinate_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subordinate_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_clause_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sentence_end, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sentence_end, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sentence_end, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sentence_end, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__sentence_end_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__sentence_end_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__sentence_end_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sentence, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sentence, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(8),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [118] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__end_dot = 0,
  ts_external_token_period = 1,
  ts_external_token_word = 2,
  ts_external_token_conjunction = 3,
  ts_external_token_subordinator = 4,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__end_dot] = sym__end_dot,
  [ts_external_token_period] = sym_period,
  [ts_external_token_word] = sym_word,
  [ts_external_token_conjunction] = sym_conjunction,
  [ts_external_token_subordinator] = sym_subordinator,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__end_dot] = true,
    [ts_external_token_period] = true,
    [ts_external_token_word] = true,
    [ts_external_token_conjunction] = true,
    [ts_external_token_subordinator] = true,
  },
  [2] = {
    [ts_external_token_period] = true,
    [ts_external_token_word] = true,
    [ts_external_token_subordinator] = true,
  },
  [3] = {
    [ts_external_token_period] = true,
    [ts_external_token_word] = true,
    [ts_external_token_conjunction] = true,
    [ts_external_token_subordinator] = true,
  },
  [4] = {
    [ts_external_token__end_dot] = true,
    [ts_external_token_conjunction] = true,
    [ts_external_token_subordinator] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_english_external_scanner_create(void);
void tree_sitter_english_external_scanner_destroy(void *);
bool tree_sitter_english_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_english_external_scanner_serialize(void *, char *);
void tree_sitter_english_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_english(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_english_external_scanner_create,
      tree_sitter_english_external_scanner_destroy,
      tree_sitter_english_external_scanner_scan,
      tree_sitter_english_external_scanner_serialize,
      tree_sitter_english_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "english",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
