/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 5
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__sentence_end_token1 = 1,
  aux_sym__sentence_end_token2 = 2,
  aux_sym__sentence_end_token3 = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  sym_paragraph_break = 6,
  anon_sym_COMMA = 7,
  sym_semicolon = 8,
  sym_colon = 9,
  sym_em_dash = 10,
  sym_quote = 11,
  sym_dotted = 12,
  sym_number = 13,
  sym__end_dot = 14,
  sym_period = 15,
  sym_word = 16,
  sym_conjunction = 17,
  sym_subordinator = 18,
  sym_source_file = 19,
  sym_paragraph = 20,
  sym_sentence = 21,
  sym__sentence_end = 22,
  sym_clause = 23,
  sym_parenthetical = 24,
  sym_complete_parenthetical = 25,
  sym_subordinate_clause = 26,
  sym__comma = 27,
  sym__wordish = 28,
  aux_sym_source_file_repeat1 = 29,
  aux_sym_source_file_repeat2 = 30,
  aux_sym_paragraph_repeat1 = 31,
  aux_sym_sentence_repeat1 = 32,
  aux_sym__sentence_end_repeat1 = 33,
  aux_sym_clause_repeat1 = 34,
  aux_sym_subordinate_clause_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__sentence_end_token1] = "_sentence_end_token1",
  [aux_sym__sentence_end_token2] = "_sentence_end_token2",
  [aux_sym__sentence_end_token3] = "_sentence_end_token3",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_paragraph_break] = "paragraph_break",
  [anon_sym_COMMA] = ",",
  [sym_semicolon] = "semicolon",
  [sym_colon] = "colon",
  [sym_em_dash] = "em_dash",
  [sym_quote] = "quote",
  [sym_dotted] = "dotted",
  [sym_number] = "number",
  [sym__end_dot] = "_end_dot",
  [sym_period] = "period",
  [sym_word] = "word",
  [sym_conjunction] = "conjunction",
  [sym_subordinator] = "subordinator",
  [sym_source_file] = "source_file",
  [sym_paragraph] = "paragraph",
  [sym_sentence] = "sentence",
  [sym__sentence_end] = "_sentence_end",
  [sym_clause] = "clause",
  [sym_parenthetical] = "parenthetical",
  [sym_complete_parenthetical] = "complete_parenthetical",
  [sym_subordinate_clause] = "subordinate_clause",
  [sym__comma] = "_comma",
  [sym__wordish] = "_wordish",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_sentence_repeat1] = "sentence_repeat1",
  [aux_sym__sentence_end_repeat1] = "_sentence_end_repeat1",
  [aux_sym_clause_repeat1] = "clause_repeat1",
  [aux_sym_subordinate_clause_repeat1] = "subordinate_clause_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__sentence_end_token1] = aux_sym__sentence_end_token1,
  [aux_sym__sentence_end_token2] = aux_sym__sentence_end_token2,
  [aux_sym__sentence_end_token3] = aux_sym__sentence_end_token3,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_paragraph_break] = sym_paragraph_break,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_semicolon] = sym_semicolon,
  [sym_colon] = sym_colon,
  [sym_em_dash] = sym_em_dash,
  [sym_quote] = sym_quote,
  [sym_dotted] = sym_dotted,
  [sym_number] = sym_number,
  [sym__end_dot] = sym__end_dot,
  [sym_period] = sym_period,
  [sym_word] = sym_word,
  [sym_conjunction] = sym_conjunction,
  [sym_subordinator] = sym_subordinator,
  [sym_source_file] = sym_source_file,
  [sym_paragraph] = sym_paragraph,
  [sym_sentence] = sym_sentence,
  [sym__sentence_end] = sym__sentence_end,
  [sym_clause] = sym_clause,
  [sym_parenthetical] = sym_parenthetical,
  [sym_complete_parenthetical] = sym_complete_parenthetical,
  [sym_subordinate_clause] = sym_subordinate_clause,
  [sym__comma] = sym__comma,
  [sym__wordish] = sym__wordish,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_sentence_repeat1] = aux_sym_sentence_repeat1,
  [aux_sym__sentence_end_repeat1] = aux_sym__sentence_end_repeat1,
  [aux_sym_clause_repeat1] = aux_sym_clause_repeat1,
  [aux_sym_subordinate_clause_repeat1] = aux_sym_subordinate_clause_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__sentence_end_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sentence_end_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sentence_end_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_paragraph_break] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_semicolon] = {
    .visible = true,
    .named = true,
  },
  [sym_colon] = {
    .visible = true,
    .named = true,
  },
  [sym_em_dash] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_dotted] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym__end_dot] = {
    .visible = false,
    .named = true,
  },
  [sym_period] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_conjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_subordinator] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym__sentence_end] = {
    .visible = false,
    .named = true,
  },
  [sym_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthetical] = {
    .visible = true,
    .named = true,
  },
  [sym_complete_parenthetical] = {
    .visible = true,
    .named = true,
  },
  [sym_subordinate_clause] = {
    .visible = true,
    .named = true,
  },
  [sym__comma] = {
    .visible = false,
    .named = true,
  },
  [sym__wordish] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sentence_end_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subordinate_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 12,
  [14] = 12,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 15,
  [19] = 19,
  [20] = 20,
  [21] = 10,
  [22] = 22,
  [23] = 23,
  [24] = 15,
  [25] = 11,
  [26] = 12,
  [27] = 9,
  [28] = 12,
  [29] = 29,
  [30] = 29,
  [31] = 29,
  [32] = 29,
  [33] = 11,
  [34] = 10,
  [35] = 29,
  [36] = 36,
  [37] = 19,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 19,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 54,
  [57] = 54,
  [58] = 58,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '(', 17,
        ')', 18,
        ',', 21,
        ':', 23,
        ';', 22,
        '!', 14,
        '?', 14,
        ']', 16,
        '}', 16,
        0x2013, 24,
        0x2014, 24,
        '"', 15,
        '\'', 15,
        0x2018, 15,
        0x2019, 15,
        0x201c, 15,
        0x201d, 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ',') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ',') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead == 0x0b ||
          lookahead == '\f') SKIP(1);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\n', 6,
        '\r', 4,
        '(', 17,
        ',', 21,
        0x2013, 24,
        0x2014, 24,
        ')', 16,
        ']', 16,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '\n', 20,
        '\r', 4,
        '(', 17,
        ',', 21,
        0x2013, 24,
        0x2014, 24,
        ')', 16,
        ']', 16,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead == 0x0b ||
          lookahead == '\f') SKIP(4);
      if (lookahead == 0x2013 ||
          lookahead == 0x2014) ADVANCE(24);
      if (lookahead == ')' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(16);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '(', 17,
        ')', 18,
        ',', 21,
        ':', 23,
        ';', 22,
        '!', 14,
        '?', 14,
        0x2013, 24,
        0x2014, 24,
        '"', 25,
        '\'', 25,
        0x2018, 25,
        0x2019, 25,
        0x201c, 25,
        0x201d, 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 10:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ',') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(11);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '\n', 6,
        '\r', 4,
        '(', 17,
        ',', 21,
        0x2013, 24,
        0x2014, 24,
        ')', 16,
        ']', 16,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(12);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2018 ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym__sentence_end_token1);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym__sentence_end_token2);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym__sentence_end_token3);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_paragraph_break);
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_paragraph_break);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_semicolon);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_colon);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_em_dash);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_quote);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_dotted);
      if (lookahead == '.') ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_dotted);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 11, .external_lex_state = 2},
  [2] = {.lex_state = 11, .external_lex_state = 2},
  [3] = {.lex_state = 11, .external_lex_state = 2},
  [4] = {.lex_state = 11, .external_lex_state = 2},
  [5] = {.lex_state = 11, .external_lex_state = 2},
  [6] = {.lex_state = 11, .external_lex_state = 2},
  [7] = {.lex_state = 11, .external_lex_state = 2},
  [8] = {.lex_state = 11, .external_lex_state = 2},
  [9] = {.lex_state = 7, .external_lex_state = 1},
  [10] = {.lex_state = 7, .external_lex_state = 1},
  [11] = {.lex_state = 7, .external_lex_state = 1},
  [12] = {.lex_state = 7, .external_lex_state = 1},
  [13] = {.lex_state = 7, .external_lex_state = 1},
  [14] = {.lex_state = 7, .external_lex_state = 1},
  [15] = {.lex_state = 7, .external_lex_state = 2},
  [16] = {.lex_state = 12, .external_lex_state = 2},
  [17] = {.lex_state = 7, .external_lex_state = 2},
  [18] = {.lex_state = 7, .external_lex_state = 2},
  [19] = {.lex_state = 7, .external_lex_state = 1},
  [20] = {.lex_state = 12, .external_lex_state = 2},
  [21] = {.lex_state = 7, .external_lex_state = 3},
  [22] = {.lex_state = 12, .external_lex_state = 2},
  [23] = {.lex_state = 7, .external_lex_state = 2},
  [24] = {.lex_state = 7, .external_lex_state = 2},
  [25] = {.lex_state = 7, .external_lex_state = 3},
  [26] = {.lex_state = 7, .external_lex_state = 4},
  [27] = {.lex_state = 7, .external_lex_state = 4},
  [28] = {.lex_state = 7, .external_lex_state = 4},
  [29] = {.lex_state = 7, .external_lex_state = 4},
  [30] = {.lex_state = 7, .external_lex_state = 4},
  [31] = {.lex_state = 7, .external_lex_state = 4},
  [32] = {.lex_state = 7, .external_lex_state = 4},
  [33] = {.lex_state = 7, .external_lex_state = 5},
  [34] = {.lex_state = 7, .external_lex_state = 5},
  [35] = {.lex_state = 7, .external_lex_state = 4},
  [36] = {.lex_state = 11, .external_lex_state = 2},
  [37] = {.lex_state = 7, .external_lex_state = 3},
  [38] = {.lex_state = 0, .external_lex_state = 6},
  [39] = {.lex_state = 11, .external_lex_state = 2},
  [40] = {.lex_state = 11, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 6},
  [42] = {.lex_state = 11, .external_lex_state = 2},
  [43] = {.lex_state = 11, .external_lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 6},
  [45] = {.lex_state = 7, .external_lex_state = 5},
  [46] = {.lex_state = 0, .external_lex_state = 6},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 11},
  [49] = {.lex_state = 11},
  [50] = {.lex_state = 11},
  [51] = {.lex_state = 11},
  [52] = {.lex_state = 7, .external_lex_state = 7},
  [53] = {.lex_state = 11},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 7},
  [58] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__sentence_end_token1] = ACTIONS(1),
    [aux_sym__sentence_end_token2] = ACTIONS(1),
    [aux_sym__sentence_end_token3] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_semicolon] = ACTIONS(1),
    [sym_colon] = ACTIONS(1),
    [sym_em_dash] = ACTIONS(1),
    [sym_quote] = ACTIONS(1),
    [sym_dotted] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym__end_dot] = ACTIONS(1),
    [sym_period] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_conjunction] = ACTIONS(1),
    [sym_subordinator] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(58),
    [sym_paragraph] = STATE(50),
    [sym_sentence] = STATE(7),
    [sym_clause] = STATE(38),
    [sym_parenthetical] = STATE(10),
    [sym_complete_parenthetical] = STATE(42),
    [sym_subordinate_clause] = STATE(38),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_clause_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_paragraph_break] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_quote] = ACTIONS(9),
    [sym_dotted] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [sym_period] = ACTIONS(11),
    [sym_word] = ACTIONS(11),
    [sym_subordinator] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym_paragraph] = STATE(53),
    [sym_sentence] = STATE(7),
    [sym_clause] = STATE(38),
    [sym_parenthetical] = STATE(10),
    [sym_complete_parenthetical] = STATE(42),
    [sym_subordinate_clause] = STATE(38),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(36),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_clause_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_paragraph_break] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_quote] = ACTIONS(9),
    [sym_dotted] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [sym_period] = ACTIONS(11),
    [sym_word] = ACTIONS(11),
    [sym_subordinator] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_paragraph] = STATE(49),
    [sym_sentence] = STATE(7),
    [sym_clause] = STATE(38),
    [sym_parenthetical] = STATE(10),
    [sym_complete_parenthetical] = STATE(42),
    [sym_subordinate_clause] = STATE(38),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(36),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_clause_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_paragraph_break] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_quote] = ACTIONS(9),
    [sym_dotted] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [sym_period] = ACTIONS(11),
    [sym_word] = ACTIONS(11),
    [sym_subordinator] = ACTIONS(13),
  },
  [STATE(4)] = {
    [sym_paragraph] = STATE(53),
    [sym_sentence] = STATE(7),
    [sym_clause] = STATE(38),
    [sym_parenthetical] = STATE(10),
    [sym_complete_parenthetical] = STATE(42),
    [sym_subordinate_clause] = STATE(38),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(36),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_clause_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_paragraph_break] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_quote] = ACTIONS(9),
    [sym_dotted] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [sym_period] = ACTIONS(11),
    [sym_word] = ACTIONS(11),
    [sym_subordinator] = ACTIONS(13),
  },
  [STATE(5)] = {
    [sym_paragraph] = STATE(53),
    [sym_sentence] = STATE(7),
    [sym_clause] = STATE(38),
    [sym_parenthetical] = STATE(10),
    [sym_complete_parenthetical] = STATE(42),
    [sym_subordinate_clause] = STATE(38),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(36),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_clause_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_paragraph_break] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_quote] = ACTIONS(9),
    [sym_dotted] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [sym_period] = ACTIONS(11),
    [sym_word] = ACTIONS(11),
    [sym_subordinator] = ACTIONS(13),
  },
  [STATE(6)] = {
    [sym_paragraph] = STATE(53),
    [sym_sentence] = STATE(7),
    [sym_clause] = STATE(38),
    [sym_parenthetical] = STATE(10),
    [sym_complete_parenthetical] = STATE(42),
    [sym_subordinate_clause] = STATE(38),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(36),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_clause_repeat1] = STATE(10),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_paragraph_break] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_quote] = ACTIONS(9),
    [sym_dotted] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [sym_period] = ACTIONS(11),
    [sym_word] = ACTIONS(11),
    [sym_subordinator] = ACTIONS(13),
  },
  [STATE(7)] = {
    [sym_sentence] = STATE(8),
    [sym_clause] = STATE(38),
    [sym_parenthetical] = STATE(10),
    [sym_complete_parenthetical] = STATE(42),
    [sym_subordinate_clause] = STATE(38),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_paragraph_repeat1] = STATE(8),
    [aux_sym_clause_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_paragraph_break] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(9),
    [sym_quote] = ACTIONS(9),
    [sym_dotted] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [sym_period] = ACTIONS(11),
    [sym_word] = ACTIONS(11),
    [sym_subordinator] = ACTIONS(13),
  },
  [STATE(8)] = {
    [sym_sentence] = STATE(8),
    [sym_clause] = STATE(38),
    [sym_parenthetical] = STATE(10),
    [sym_complete_parenthetical] = STATE(42),
    [sym_subordinate_clause] = STATE(38),
    [sym__comma] = STATE(10),
    [sym__wordish] = STATE(10),
    [aux_sym_paragraph_repeat1] = STATE(8),
    [aux_sym_clause_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [sym_paragraph_break] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(32),
    [sym_quote] = ACTIONS(32),
    [sym_dotted] = ACTIONS(32),
    [sym_number] = ACTIONS(32),
    [sym_period] = ACTIONS(35),
    [sym_word] = ACTIONS(35),
    [sym_subordinator] = ACTIONS(38),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(46), 1,
      sym_subordinator,
    STATE(9), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(41), 6,
      sym__end_dot,
      aux_sym__sentence_end_token1,
      anon_sym_RPAREN,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
    ACTIONS(43), 7,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [27] = 4,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    STATE(11), 4,
      sym_parenthetical,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(53), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
    ACTIONS(49), 7,
      sym__end_dot,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [54] = 4,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    STATE(11), 4,
      sym_parenthetical,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(60), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
    ACTIONS(55), 7,
      sym__end_dot,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [81] = 2,
    STATE(9), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(63), 14,
      sym__end_dot,
      sym_period,
      sym_word,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
      sym_quote,
      sym_dotted,
      sym_number,
  [104] = 3,
    STATE(9), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(65), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
    ACTIONS(63), 7,
      sym__end_dot,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [128] = 4,
    ACTIONS(67), 1,
      sym_subordinator,
    ACTIONS(63), 3,
      sym__end_dot,
      aux_sym__sentence_end_token1,
      anon_sym_RPAREN,
    STATE(9), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(65), 7,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [152] = 5,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      sym_subordinator,
    STATE(56), 2,
      sym_clause,
      sym_subordinate_clause,
    STATE(34), 4,
      sym_parenthetical,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(71), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [177] = 4,
    STATE(22), 1,
      aux_sym__sentence_end_repeat1,
    ACTIONS(77), 3,
      aux_sym__sentence_end_token2,
      aux_sym__sentence_end_token3,
      sym_em_dash,
    ACTIONS(75), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
    ACTIONS(79), 5,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [200] = 5,
    ACTIONS(13), 1,
      sym_subordinator,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    STATE(46), 2,
      sym_clause,
      sym_subordinate_clause,
    STATE(10), 4,
      sym_parenthetical,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(11), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [225] = 5,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      sym_subordinator,
    STATE(54), 2,
      sym_clause,
      sym_subordinate_clause,
    STATE(34), 4,
      sym_parenthetical,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(71), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [250] = 1,
    ACTIONS(81), 14,
      sym__end_dot,
      sym_period,
      sym_word,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
      sym_quote,
      sym_dotted,
      sym_number,
  [267] = 4,
    STATE(20), 1,
      aux_sym__sentence_end_repeat1,
    ACTIONS(85), 3,
      aux_sym__sentence_end_token2,
      aux_sym__sentence_end_token3,
      sym_em_dash,
    ACTIONS(83), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
    ACTIONS(88), 5,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [290] = 4,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 3,
      sym__end_dot,
      aux_sym__sentence_end_token1,
      anon_sym_RPAREN,
    STATE(25), 4,
      sym_parenthetical,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(92), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [313] = 4,
    STATE(20), 1,
      aux_sym__sentence_end_repeat1,
    ACTIONS(96), 3,
      aux_sym__sentence_end_token2,
      aux_sym__sentence_end_token3,
      sym_em_dash,
    ACTIONS(94), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
    ACTIONS(98), 5,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [336] = 5,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(102), 1,
      sym_subordinator,
    STATE(52), 2,
      sym_clause,
      sym_subordinate_clause,
    STATE(21), 4,
      sym_parenthetical,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(100), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [361] = 5,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      sym_subordinator,
    STATE(57), 2,
      sym_clause,
      sym_subordinate_clause,
    STATE(34), 4,
      sym_parenthetical,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(71), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [386] = 4,
    ACTIONS(104), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 3,
      sym__end_dot,
      aux_sym__sentence_end_token1,
      anon_sym_RPAREN,
    STATE(25), 4,
      sym_parenthetical,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(107), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [409] = 4,
    ACTIONS(63), 1,
      anon_sym_RPAREN,
    ACTIONS(112), 1,
      sym_subordinator,
    STATE(27), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(110), 7,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [431] = 4,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
    ACTIONS(117), 1,
      sym_subordinator,
    STATE(27), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(114), 7,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [453] = 2,
    STATE(27), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(63), 9,
      sym_period,
      sym_word,
      sym_conjunction,
      sym_subordinator,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [471] = 3,
    ACTIONS(67), 1,
      sym_subordinator,
    STATE(13), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(120), 7,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [490] = 3,
    ACTIONS(67), 1,
      sym_subordinator,
    STATE(14), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(122), 7,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [509] = 3,
    ACTIONS(67), 1,
      sym_subordinator,
    STATE(12), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(124), 7,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [528] = 3,
    ACTIONS(112), 1,
      sym_subordinator,
    STATE(26), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(126), 7,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [547] = 4,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    STATE(33), 4,
      sym_parenthetical,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(131), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [568] = 4,
    ACTIONS(49), 1,
      anon_sym_RPAREN,
    ACTIONS(69), 1,
      anon_sym_LPAREN,
    STATE(33), 4,
      sym_parenthetical,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(134), 6,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [589] = 3,
    ACTIONS(112), 1,
      sym_subordinator,
    STATE(28), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(136), 7,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [608] = 4,
    ACTIONS(142), 1,
      sym_paragraph_break,
    STATE(36), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(138), 4,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
    ACTIONS(140), 5,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [628] = 1,
    ACTIONS(81), 10,
      sym__end_dot,
      sym_period,
      sym_word,
      aux_sym__sentence_end_token1,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [641] = 5,
    ACTIONS(13), 1,
      sym_subordinator,
    STATE(39), 1,
      sym__sentence_end,
    ACTIONS(145), 2,
      sym__end_dot,
      aux_sym__sentence_end_token1,
    STATE(41), 2,
      sym_subordinate_clause,
      aux_sym_sentence_repeat1,
    ACTIONS(147), 4,
      sym_conjunction,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [662] = 2,
    ACTIONS(149), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
    ACTIONS(151), 5,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [677] = 2,
    ACTIONS(153), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
    ACTIONS(155), 5,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [692] = 5,
    ACTIONS(13), 1,
      sym_subordinator,
    STATE(43), 1,
      sym__sentence_end,
    ACTIONS(145), 2,
      sym__end_dot,
      aux_sym__sentence_end_token1,
    STATE(44), 2,
      sym_subordinate_clause,
      aux_sym_sentence_repeat1,
    ACTIONS(147), 4,
      sym_conjunction,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [713] = 2,
    ACTIONS(157), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
    ACTIONS(159), 5,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [728] = 2,
    ACTIONS(161), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
    ACTIONS(163), 5,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [743] = 4,
    ACTIONS(170), 1,
      sym_subordinator,
    ACTIONS(165), 2,
      sym__end_dot,
      aux_sym__sentence_end_token1,
    STATE(44), 2,
      sym_subordinate_clause,
      aux_sym_sentence_repeat1,
    ACTIONS(167), 4,
      sym_conjunction,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [761] = 1,
    ACTIONS(81), 8,
      sym_period,
      sym_word,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_quote,
      sym_dotted,
      sym_number,
  [772] = 1,
    ACTIONS(165), 7,
      sym__end_dot,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
      sym_semicolon,
      sym_colon,
      sym_em_dash,
  [782] = 4,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(173), 1,
      sym_paragraph_break,
    STATE(5), 1,
      aux_sym_source_file_repeat1,
    STATE(48), 1,
      aux_sym_source_file_repeat2,
  [795] = 4,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
    ACTIONS(177), 1,
      sym_paragraph_break,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(48), 1,
      aux_sym_source_file_repeat2,
  [808] = 4,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(180), 1,
      sym_paragraph_break,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(47), 1,
      aux_sym_source_file_repeat2,
  [821] = 4,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 1,
      sym_paragraph_break,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(51), 1,
      aux_sym_source_file_repeat2,
  [834] = 4,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(180), 1,
      sym_paragraph_break,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(48), 1,
      aux_sym_source_file_repeat2,
  [847] = 2,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    ACTIONS(184), 2,
      sym__end_dot,
      aux_sym__sentence_end_token1,
  [855] = 1,
    ACTIONS(175), 2,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [860] = 1,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
  [864] = 1,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
  [868] = 1,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
  [872] = 1,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
  [876] = 1,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 27,
  [SMALL_STATE(11)] = 54,
  [SMALL_STATE(12)] = 81,
  [SMALL_STATE(13)] = 104,
  [SMALL_STATE(14)] = 128,
  [SMALL_STATE(15)] = 152,
  [SMALL_STATE(16)] = 177,
  [SMALL_STATE(17)] = 200,
  [SMALL_STATE(18)] = 225,
  [SMALL_STATE(19)] = 250,
  [SMALL_STATE(20)] = 267,
  [SMALL_STATE(21)] = 290,
  [SMALL_STATE(22)] = 313,
  [SMALL_STATE(23)] = 336,
  [SMALL_STATE(24)] = 361,
  [SMALL_STATE(25)] = 386,
  [SMALL_STATE(26)] = 409,
  [SMALL_STATE(27)] = 431,
  [SMALL_STATE(28)] = 453,
  [SMALL_STATE(29)] = 471,
  [SMALL_STATE(30)] = 490,
  [SMALL_STATE(31)] = 509,
  [SMALL_STATE(32)] = 528,
  [SMALL_STATE(33)] = 547,
  [SMALL_STATE(34)] = 568,
  [SMALL_STATE(35)] = 589,
  [SMALL_STATE(36)] = 608,
  [SMALL_STATE(37)] = 628,
  [SMALL_STATE(38)] = 641,
  [SMALL_STATE(39)] = 662,
  [SMALL_STATE(40)] = 677,
  [SMALL_STATE(41)] = 692,
  [SMALL_STATE(42)] = 713,
  [SMALL_STATE(43)] = 728,
  [SMALL_STATE(44)] = 743,
  [SMALL_STATE(45)] = 761,
  [SMALL_STATE(46)] = 772,
  [SMALL_STATE(47)] = 782,
  [SMALL_STATE(48)] = 795,
  [SMALL_STATE(49)] = 808,
  [SMALL_STATE(50)] = 821,
  [SMALL_STATE(51)] = 834,
  [SMALL_STATE(52)] = 847,
  [SMALL_STATE(53)] = 855,
  [SMALL_STATE(54)] = 860,
  [SMALL_STATE(55)] = 864,
  [SMALL_STATE(56)] = 868,
  [SMALL_STATE(57)] = 872,
  [SMALL_STATE(58)] = 876,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subordinate_clause_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subordinate_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subordinate_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_clause_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subordinate_clause, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sentence_end, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sentence_end, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthetical, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__sentence_end_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__sentence_end_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__sentence_end_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sentence_end, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sentence_end, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subordinate_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subordinate_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sentence, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_complete_parenthetical, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_complete_parenthetical, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sentence, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sentence, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(6),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [194] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__end_dot = 0,
  ts_external_token_period = 1,
  ts_external_token_word = 2,
  ts_external_token_conjunction = 3,
  ts_external_token_subordinator = 4,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__end_dot] = sym__end_dot,
  [ts_external_token_period] = sym_period,
  [ts_external_token_word] = sym_word,
  [ts_external_token_conjunction] = sym_conjunction,
  [ts_external_token_subordinator] = sym_subordinator,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__end_dot] = true,
    [ts_external_token_period] = true,
    [ts_external_token_word] = true,
    [ts_external_token_conjunction] = true,
    [ts_external_token_subordinator] = true,
  },
  [2] = {
    [ts_external_token_period] = true,
    [ts_external_token_word] = true,
    [ts_external_token_subordinator] = true,
  },
  [3] = {
    [ts_external_token__end_dot] = true,
    [ts_external_token_period] = true,
    [ts_external_token_word] = true,
  },
  [4] = {
    [ts_external_token_period] = true,
    [ts_external_token_word] = true,
    [ts_external_token_conjunction] = true,
    [ts_external_token_subordinator] = true,
  },
  [5] = {
    [ts_external_token_period] = true,
    [ts_external_token_word] = true,
  },
  [6] = {
    [ts_external_token__end_dot] = true,
    [ts_external_token_conjunction] = true,
    [ts_external_token_subordinator] = true,
  },
  [7] = {
    [ts_external_token__end_dot] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_english_external_scanner_create(void);
void tree_sitter_english_external_scanner_destroy(void *);
bool tree_sitter_english_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_english_external_scanner_serialize(void *, char *);
void tree_sitter_english_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_english(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_english_external_scanner_create,
      tree_sitter_english_external_scanner_destroy,
      tree_sitter_english_external_scanner_scan,
      tree_sitter_english_external_scanner_serialize,
      tree_sitter_english_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "english",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
