/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 34
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 5
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__sentence_end_token1 = 1,
  aux_sym__sentence_end_token2 = 2,
  aux_sym__sentence_end_token3 = 3,
  sym_paragraph_break = 4,
  anon_sym_COMMA = 5,
  sym_dotted = 6,
  sym_number = 7,
  sym__end_dot = 8,
  sym_period = 9,
  sym_word = 10,
  sym_conjunction = 11,
  sym_subordinator = 12,
  sym_source_file = 13,
  sym_paragraph = 14,
  sym_sentence = 15,
  sym__sentence_end = 16,
  sym_clause = 17,
  sym_subordinate_clause = 18,
  sym__comma = 19,
  sym__wordish = 20,
  aux_sym_source_file_repeat1 = 21,
  aux_sym_source_file_repeat2 = 22,
  aux_sym_paragraph_repeat1 = 23,
  aux_sym_sentence_repeat1 = 24,
  aux_sym__sentence_end_repeat1 = 25,
  aux_sym_clause_repeat1 = 26,
  aux_sym_subordinate_clause_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__sentence_end_token1] = "_sentence_end_token1",
  [aux_sym__sentence_end_token2] = "_sentence_end_token2",
  [aux_sym__sentence_end_token3] = "_sentence_end_token3",
  [sym_paragraph_break] = "paragraph_break",
  [anon_sym_COMMA] = ",",
  [sym_dotted] = "dotted",
  [sym_number] = "number",
  [sym__end_dot] = "_end_dot",
  [sym_period] = "period",
  [sym_word] = "word",
  [sym_conjunction] = "conjunction",
  [sym_subordinator] = "subordinator",
  [sym_source_file] = "source_file",
  [sym_paragraph] = "paragraph",
  [sym_sentence] = "sentence",
  [sym__sentence_end] = "_sentence_end",
  [sym_clause] = "clause",
  [sym_subordinate_clause] = "subordinate_clause",
  [sym__comma] = "_comma",
  [sym__wordish] = "_wordish",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_sentence_repeat1] = "sentence_repeat1",
  [aux_sym__sentence_end_repeat1] = "_sentence_end_repeat1",
  [aux_sym_clause_repeat1] = "clause_repeat1",
  [aux_sym_subordinate_clause_repeat1] = "subordinate_clause_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__sentence_end_token1] = aux_sym__sentence_end_token1,
  [aux_sym__sentence_end_token2] = aux_sym__sentence_end_token2,
  [aux_sym__sentence_end_token3] = aux_sym__sentence_end_token3,
  [sym_paragraph_break] = sym_paragraph_break,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_dotted] = sym_dotted,
  [sym_number] = sym_number,
  [sym__end_dot] = sym__end_dot,
  [sym_period] = sym_period,
  [sym_word] = sym_word,
  [sym_conjunction] = sym_conjunction,
  [sym_subordinator] = sym_subordinator,
  [sym_source_file] = sym_source_file,
  [sym_paragraph] = sym_paragraph,
  [sym_sentence] = sym_sentence,
  [sym__sentence_end] = sym__sentence_end,
  [sym_clause] = sym_clause,
  [sym_subordinate_clause] = sym_subordinate_clause,
  [sym__comma] = sym__comma,
  [sym__wordish] = sym__wordish,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_sentence_repeat1] = aux_sym_sentence_repeat1,
  [aux_sym__sentence_end_repeat1] = aux_sym__sentence_end_repeat1,
  [aux_sym_clause_repeat1] = aux_sym_clause_repeat1,
  [aux_sym_subordinate_clause_repeat1] = aux_sym_subordinate_clause_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__sentence_end_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sentence_end_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sentence_end_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_paragraph_break] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_dotted] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym__end_dot] = {
    .visible = false,
    .named = true,
  },
  [sym_period] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_conjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_subordinator] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym__sentence_end] = {
    .visible = false,
    .named = true,
  },
  [sym_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_subordinate_clause] = {
    .visible = true,
    .named = true,
  },
  [sym__comma] = {
    .visible = false,
    .named = true,
  },
  [sym__wordish] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sentence_end_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subordinate_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 15,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        ',', 13,
        '!', 9,
        '?', 9,
        ')', 11,
        ']', 11,
        '}', 11,
        '"', 10,
        '\'', 10,
        0x2019, 10,
        0x201c, 10,
        0x201d, 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == ')' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == ')' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead == 0x0b ||
          lookahead == '\f') SKIP(1);
      if (lookahead == ')' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(11);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 6:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == ')' ||
          lookahead == ']' ||
          lookahead == '}') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == 0x2019 ||
          lookahead == 0x201c ||
          lookahead == 0x201d) ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym__sentence_end_token1);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym__sentence_end_token2);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym__sentence_end_token3);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_paragraph_break);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_dotted);
      if (lookahead == '.') ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_dotted);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 7, .external_lex_state = 2},
  [2] = {.lex_state = 7, .external_lex_state = 2},
  [3] = {.lex_state = 7, .external_lex_state = 2},
  [4] = {.lex_state = 7, .external_lex_state = 2},
  [5] = {.lex_state = 7, .external_lex_state = 2},
  [6] = {.lex_state = 7, .external_lex_state = 2},
  [7] = {.lex_state = 7, .external_lex_state = 2},
  [8] = {.lex_state = 7, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 1},
  [10] = {.lex_state = 0, .external_lex_state = 1},
  [11] = {.lex_state = 0, .external_lex_state = 1},
  [12] = {.lex_state = 0, .external_lex_state = 1},
  [13] = {.lex_state = 0, .external_lex_state = 1},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 3},
  [16] = {.lex_state = 7, .external_lex_state = 2},
  [17] = {.lex_state = 7, .external_lex_state = 2},
  [18] = {.lex_state = 7, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 3},
  [20] = {.lex_state = 7, .external_lex_state = 2},
  [21] = {.lex_state = 7, .external_lex_state = 2},
  [22] = {.lex_state = 7, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 4},
  [24] = {.lex_state = 0, .external_lex_state = 4},
  [25] = {.lex_state = 0, .external_lex_state = 4},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 0, .external_lex_state = 4},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__sentence_end_token1] = ACTIONS(1),
    [aux_sym__sentence_end_token2] = ACTIONS(1),
    [aux_sym__sentence_end_token3] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_dotted] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym__end_dot] = ACTIONS(1),
    [sym_period] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_conjunction] = ACTIONS(1),
    [sym_subordinator] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(33),
    [sym_paragraph] = STATE(28),
    [sym_sentence] = STATE(7),
    [sym_clause] = STATE(23),
    [sym_subordinate_clause] = STATE(23),
    [sym__comma] = STATE(12),
    [sym__wordish] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_clause_repeat1] = STATE(12),
    [sym_paragraph_break] = ACTIONS(3),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_paragraph] = STATE(32),
    [sym_sentence] = STATE(7),
    [sym_clause] = STATE(23),
    [sym_subordinate_clause] = STATE(23),
    [sym__comma] = STATE(12),
    [sym__wordish] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(20),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_clause_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_paragraph_break] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym_paragraph] = STATE(32),
    [sym_sentence] = STATE(7),
    [sym_clause] = STATE(23),
    [sym_subordinate_clause] = STATE(23),
    [sym__comma] = STATE(12),
    [sym__wordish] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(20),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_clause_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_paragraph_break] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(4)] = {
    [sym_paragraph] = STATE(32),
    [sym_sentence] = STATE(7),
    [sym_clause] = STATE(23),
    [sym_subordinate_clause] = STATE(23),
    [sym__comma] = STATE(12),
    [sym__wordish] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(20),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_clause_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_paragraph_break] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(5)] = {
    [sym_paragraph] = STATE(27),
    [sym_sentence] = STATE(7),
    [sym_clause] = STATE(23),
    [sym_subordinate_clause] = STATE(23),
    [sym__comma] = STATE(12),
    [sym__wordish] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(20),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_clause_repeat1] = STATE(12),
    [sym_paragraph_break] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(6)] = {
    [sym_paragraph] = STATE(32),
    [sym_sentence] = STATE(7),
    [sym_clause] = STATE(23),
    [sym_subordinate_clause] = STATE(23),
    [sym__comma] = STATE(12),
    [sym__wordish] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(20),
    [aux_sym_paragraph_repeat1] = STATE(7),
    [aux_sym_clause_repeat1] = STATE(12),
    [sym_paragraph_break] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(7)] = {
    [sym_sentence] = STATE(8),
    [sym_clause] = STATE(23),
    [sym_subordinate_clause] = STATE(23),
    [sym__comma] = STATE(12),
    [sym__wordish] = STATE(12),
    [aux_sym_paragraph_repeat1] = STATE(8),
    [aux_sym_clause_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_paragraph_break] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(5),
    [sym_dotted] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_period] = ACTIONS(7),
    [sym_word] = ACTIONS(7),
    [sym_subordinator] = ACTIONS(9),
  },
  [STATE(8)] = {
    [sym_sentence] = STATE(8),
    [sym_clause] = STATE(23),
    [sym_subordinate_clause] = STATE(23),
    [sym__comma] = STATE(12),
    [sym__wordish] = STATE(12),
    [aux_sym_paragraph_repeat1] = STATE(8),
    [aux_sym_clause_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_paragraph_break] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
    [sym_dotted] = ACTIONS(23),
    [sym_number] = ACTIONS(23),
    [sym_period] = ACTIONS(26),
    [sym_word] = ACTIONS(26),
    [sym_subordinator] = ACTIONS(29),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(32), 4,
      sym__end_dot,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
    STATE(11), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(34), 5,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
  [20] = 2,
    STATE(11), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(32), 9,
      sym__end_dot,
      sym_period,
      sym_word,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
  [38] = 4,
    ACTIONS(41), 1,
      sym_subordinator,
    ACTIONS(36), 2,
      sym__end_dot,
      aux_sym__sentence_end_token1,
    STATE(11), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(38), 6,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
  [60] = 3,
    STATE(13), 3,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(44), 4,
      sym__end_dot,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
    ACTIONS(46), 5,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
  [79] = 3,
    STATE(13), 3,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(48), 4,
      sym__end_dot,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
    ACTIONS(50), 5,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
  [98] = 4,
    ACTIONS(9), 1,
      sym_subordinator,
    STATE(31), 2,
      sym_clause,
      sym_subordinate_clause,
    STATE(12), 3,
      sym__comma,
      sym__wordish,
      aux_sym_clause_repeat1,
    ACTIONS(7), 5,
      sym_period,
      sym_word,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
  [118] = 3,
    ACTIONS(55), 1,
      sym_subordinator,
    STATE(9), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(53), 6,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
  [136] = 4,
    STATE(17), 1,
      aux_sym__sentence_end_repeat1,
    ACTIONS(59), 2,
      aux_sym__sentence_end_token2,
      aux_sym__sentence_end_token3,
    ACTIONS(61), 3,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
    ACTIONS(57), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [156] = 4,
    STATE(18), 1,
      aux_sym__sentence_end_repeat1,
    ACTIONS(65), 2,
      aux_sym__sentence_end_token2,
      aux_sym__sentence_end_token3,
    ACTIONS(67), 3,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
    ACTIONS(63), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [176] = 4,
    STATE(18), 1,
      aux_sym__sentence_end_repeat1,
    ACTIONS(71), 2,
      aux_sym__sentence_end_token2,
      aux_sym__sentence_end_token3,
    ACTIONS(74), 3,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
    ACTIONS(69), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [196] = 3,
    ACTIONS(55), 1,
      sym_subordinator,
    STATE(10), 4,
      sym_subordinate_clause,
      sym__comma,
      sym__wordish,
      aux_sym_subordinate_clause_repeat1,
    ACTIONS(76), 6,
      sym_period,
      sym_word,
      sym_conjunction,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
  [214] = 4,
    ACTIONS(80), 1,
      sym_paragraph_break,
    STATE(20), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(83), 3,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
    ACTIONS(78), 4,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
  [232] = 2,
    ACTIONS(87), 3,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
    ACTIONS(85), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [245] = 2,
    ACTIONS(91), 3,
      anon_sym_COMMA,
      sym_dotted,
      sym_number,
    ACTIONS(89), 5,
      sym_period,
      sym_word,
      sym_subordinator,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [258] = 5,
    ACTIONS(9), 1,
      sym_subordinator,
    ACTIONS(95), 1,
      sym_conjunction,
    STATE(21), 1,
      sym__sentence_end,
    ACTIONS(93), 2,
      sym__end_dot,
      aux_sym__sentence_end_token1,
    STATE(24), 2,
      sym_subordinate_clause,
      aux_sym_sentence_repeat1,
  [276] = 5,
    ACTIONS(9), 1,
      sym_subordinator,
    ACTIONS(95), 1,
      sym_conjunction,
    STATE(22), 1,
      sym__sentence_end,
    ACTIONS(93), 2,
      sym__end_dot,
      aux_sym__sentence_end_token1,
    STATE(25), 2,
      sym_subordinate_clause,
      aux_sym_sentence_repeat1,
  [294] = 4,
    ACTIONS(99), 1,
      sym_conjunction,
    ACTIONS(102), 1,
      sym_subordinator,
    ACTIONS(97), 2,
      sym__end_dot,
      aux_sym__sentence_end_token1,
    STATE(25), 2,
      sym_subordinate_clause,
      aux_sym_sentence_repeat1,
  [309] = 4,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 1,
      sym_paragraph_break,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(29), 1,
      aux_sym_source_file_repeat2,
  [322] = 4,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      sym_paragraph_break,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(26), 1,
      aux_sym_source_file_repeat2,
  [335] = 4,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      sym_paragraph_break,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(30), 1,
      aux_sym_source_file_repeat2,
  [348] = 4,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(115), 1,
      sym_paragraph_break,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(29), 1,
      aux_sym_source_file_repeat2,
  [361] = 4,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      sym_paragraph_break,
    STATE(4), 1,
      aux_sym_source_file_repeat1,
    STATE(29), 1,
      aux_sym_source_file_repeat2,
  [374] = 1,
    ACTIONS(97), 4,
      sym__end_dot,
      sym_conjunction,
      sym_subordinator,
      aux_sym__sentence_end_token1,
  [381] = 1,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      sym_paragraph_break,
  [386] = 1,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 20,
  [SMALL_STATE(11)] = 38,
  [SMALL_STATE(12)] = 60,
  [SMALL_STATE(13)] = 79,
  [SMALL_STATE(14)] = 98,
  [SMALL_STATE(15)] = 118,
  [SMALL_STATE(16)] = 136,
  [SMALL_STATE(17)] = 156,
  [SMALL_STATE(18)] = 176,
  [SMALL_STATE(19)] = 196,
  [SMALL_STATE(20)] = 214,
  [SMALL_STATE(21)] = 232,
  [SMALL_STATE(22)] = 245,
  [SMALL_STATE(23)] = 258,
  [SMALL_STATE(24)] = 276,
  [SMALL_STATE(25)] = 294,
  [SMALL_STATE(26)] = 309,
  [SMALL_STATE(27)] = 322,
  [SMALL_STATE(28)] = 335,
  [SMALL_STATE(29)] = 348,
  [SMALL_STATE(30)] = 361,
  [SMALL_STATE(31)] = 374,
  [SMALL_STATE(32)] = 381,
  [SMALL_STATE(33)] = 386,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subordinate_clause, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subordinate_clause_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subordinate_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_subordinate_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_clause_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_clause_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sentence_end, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sentence_end, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sentence_end, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sentence_end, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__sentence_end_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__sentence_end_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__sentence_end_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sentence, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sentence, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(6),
  [118] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__end_dot = 0,
  ts_external_token_period = 1,
  ts_external_token_word = 2,
  ts_external_token_conjunction = 3,
  ts_external_token_subordinator = 4,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__end_dot] = sym__end_dot,
  [ts_external_token_period] = sym_period,
  [ts_external_token_word] = sym_word,
  [ts_external_token_conjunction] = sym_conjunction,
  [ts_external_token_subordinator] = sym_subordinator,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__end_dot] = true,
    [ts_external_token_period] = true,
    [ts_external_token_word] = true,
    [ts_external_token_conjunction] = true,
    [ts_external_token_subordinator] = true,
  },
  [2] = {
    [ts_external_token_period] = true,
    [ts_external_token_word] = true,
    [ts_external_token_subordinator] = true,
  },
  [3] = {
    [ts_external_token_period] = true,
    [ts_external_token_word] = true,
    [ts_external_token_conjunction] = true,
    [ts_external_token_subordinator] = true,
  },
  [4] = {
    [ts_external_token__end_dot] = true,
    [ts_external_token_conjunction] = true,
    [ts_external_token_subordinator] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_english_external_scanner_create(void);
void tree_sitter_english_external_scanner_destroy(void *);
bool tree_sitter_english_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_english_external_scanner_serialize(void *, char *);
void tree_sitter_english_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_english(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_english_external_scanner_create,
      tree_sitter_english_external_scanner_destroy,
      tree_sitter_english_external_scanner_scan,
      tree_sitter_english_external_scanner_serialize,
      tree_sitter_english_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "english",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
